<?php


/**
 * This class adds structure of 'student_examination_repproved_subject' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Aug 23 21:09:09 2018
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class StudentExaminationRepprovedSubjectMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.StudentExaminationRepprovedSubjectMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(StudentExaminationRepprovedSubjectPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(StudentExaminationRepprovedSubjectPeer::TABLE_NAME);
		$tMap->setPhpName('StudentExaminationRepprovedSubject');
		$tMap->setClassname('StudentExaminationRepprovedSubject');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('STUDENT_REPPROVED_COURSE_SUBJECT_ID', 'StudentRepprovedCourseSubjectId', 'INTEGER', 'student_repproved_course_subject', 'ID', true, null);

		$tMap->addForeignKey('EXAMINATION_REPPROVED_SUBJECT_ID', 'ExaminationRepprovedSubjectId', 'INTEGER', 'examination_repproved_subject', 'ID', false, null);

		$tMap->addColumn('MARK', 'Mark', 'DECIMAL', false, 5);

		$tMap->addColumn('IS_ABSENT', 'IsAbsent', 'BOOLEAN', false, null);

		$tMap->addColumn('DATE', 'Date', 'DATE', false, null);

		$tMap->addColumn('FOLIO_NUMBER', 'FolioNumber', 'VARCHAR', false, 20);

	} // doBuild()

} // StudentExaminationRepprovedSubjectMapBuilder
