<?php


/**
 * This class adds structure of 'student_advice' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Aug 23 21:09:10 2018
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class StudentDisciplinarySanctionMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.StudentDisciplinarySanctionMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(StudentDisciplinarySanctionPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(StudentDisciplinarySanctionPeer::TABLE_NAME);
		$tMap->setPhpName('StudentDisciplinarySanction');
		$tMap->setClassname('StudentDisciplinarySanction');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('NUMBER', 'Number', 'VARCHAR', false, 11);

		$tMap->addColumn('NAME', 'Name', 'VARCHAR', false, 255);

		$tMap->addForeignKey('STUDENT_ID', 'StudentId', 'INTEGER', 'student', 'ID', true, null);

		$tMap->addColumn('REQUEST_DATE', 'RequestDate', 'DATE', true, null);

		$tMap->addColumn('RESOLUTION_DATE', 'ResolutionDate', 'DATE', false, null);

		$tMap->addColumn('VALUE', 'Value', 'DECIMAL', true, null);

		$tMap->addForeignKey('DISCIPLINARY_SANCTION_TYPE_ID', 'DisciplinarySanctionTypeId', 'INTEGER', 'disciplinary_sanction_type', 'ID', true, null);

		$tMap->addForeignKey('SANCTION_TYPE_ID', 'SanctionTypeId', 'INTEGER', 'sanction_type', 'ID', true, null);

		$tMap->addColumn('OBSERVATION', 'Observation', 'LONGVARCHAR', false, null);

		$tMap->addColumn('DOCUMENT', 'Document', 'VARCHAR', false, 255);

		$tMap->addForeignKey('APPLICANT_ID', 'ApplicantId', 'INTEGER', 'person', 'ID', false, null);

		$tMap->addColumn('APPLICANT_OTHER', 'ApplicantOther', 'VARCHAR', false, 255);

		$tMap->addForeignKey('RESPONSIBLE_ID', 'ResponsibleId', 'INTEGER', 'person', 'ID', false, null);

		$tMap->addForeignKey('SCHOOL_YEAR_ID', 'SchoolYearId', 'INTEGER', 'school_year', 'ID', true, null);

	} // doBuild()

} // StudentDisciplinarySanctionMapBuilder
