<?php

/**
 * Base static class for performing query and update operations on the 'career_subject' table.
 *
 * Cada tupla representa una carrera, una materia y el año
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Aug 23 21:09:09 2018
 *
 * @package    lib.model.om
 */
abstract class BaseCareerSubjectPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'career_subject';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.CareerSubject';

	/** The total number of columns. */
	const NUM_COLUMNS = 10;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'career_subject.ID';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'career_subject.CREATED_AT';

	/** the column name for the CAREER_ID field */
	const CAREER_ID = 'career_subject.CAREER_ID';

	/** the column name for the SUBJECT_ID field */
	const SUBJECT_ID = 'career_subject.SUBJECT_ID';

	/** the column name for the YEAR field */
	const YEAR = 'career_subject.YEAR';

	/** the column name for the HAS_OPTIONS field */
	const HAS_OPTIONS = 'career_subject.HAS_OPTIONS';

	/** the column name for the IS_OPTION field */
	const IS_OPTION = 'career_subject.IS_OPTION';

	/** the column name for the ORIENTATION_ID field */
	const ORIENTATION_ID = 'career_subject.ORIENTATION_ID';

	/** the column name for the SUB_ORIENTATION_ID field */
	const SUB_ORIENTATION_ID = 'career_subject.SUB_ORIENTATION_ID';

	/** the column name for the HAS_CORRELATIVE_PREVIOUS_YEAR field */
	const HAS_CORRELATIVE_PREVIOUS_YEAR = 'career_subject.HAS_CORRELATIVE_PREVIOUS_YEAR';

	/**
	 * An identiy map to hold any loaded instances of CareerSubject objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array CareerSubject[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'CreatedAt', 'CareerId', 'SubjectId', 'Year', 'HasOptions', 'IsOption', 'OrientationId', 'SubOrientationId', 'HasCorrelativePreviousYear', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'createdAt', 'careerId', 'subjectId', 'year', 'hasOptions', 'isOption', 'orientationId', 'subOrientationId', 'hasCorrelativePreviousYear', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::CREATED_AT, self::CAREER_ID, self::SUBJECT_ID, self::YEAR, self::HAS_OPTIONS, self::IS_OPTION, self::ORIENTATION_ID, self::SUB_ORIENTATION_ID, self::HAS_CORRELATIVE_PREVIOUS_YEAR, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'created_at', 'career_id', 'subject_id', 'year', 'has_options', 'is_option', 'orientation_id', 'sub_orientation_id', 'has_correlative_previous_year', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'CreatedAt' => 1, 'CareerId' => 2, 'SubjectId' => 3, 'Year' => 4, 'HasOptions' => 5, 'IsOption' => 6, 'OrientationId' => 7, 'SubOrientationId' => 8, 'HasCorrelativePreviousYear' => 9, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'createdAt' => 1, 'careerId' => 2, 'subjectId' => 3, 'year' => 4, 'hasOptions' => 5, 'isOption' => 6, 'orientationId' => 7, 'subOrientationId' => 8, 'hasCorrelativePreviousYear' => 9, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::CREATED_AT => 1, self::CAREER_ID => 2, self::SUBJECT_ID => 3, self::YEAR => 4, self::HAS_OPTIONS => 5, self::IS_OPTION => 6, self::ORIENTATION_ID => 7, self::SUB_ORIENTATION_ID => 8, self::HAS_CORRELATIVE_PREVIOUS_YEAR => 9, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'created_at' => 1, 'career_id' => 2, 'subject_id' => 3, 'year' => 4, 'has_options' => 5, 'is_option' => 6, 'orientation_id' => 7, 'sub_orientation_id' => 8, 'has_correlative_previous_year' => 9, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new CareerSubjectMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. CareerSubjectPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(CareerSubjectPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(CareerSubjectPeer::ID);

		$criteria->addSelectColumn(CareerSubjectPeer::CREATED_AT);

		$criteria->addSelectColumn(CareerSubjectPeer::CAREER_ID);

		$criteria->addSelectColumn(CareerSubjectPeer::SUBJECT_ID);

		$criteria->addSelectColumn(CareerSubjectPeer::YEAR);

		$criteria->addSelectColumn(CareerSubjectPeer::HAS_OPTIONS);

		$criteria->addSelectColumn(CareerSubjectPeer::IS_OPTION);

		$criteria->addSelectColumn(CareerSubjectPeer::ORIENTATION_ID);

		$criteria->addSelectColumn(CareerSubjectPeer::SUB_ORIENTATION_ID);

		$criteria->addSelectColumn(CareerSubjectPeer::HAS_CORRELATIVE_PREVIOUS_YEAR);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(CareerSubjectPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CareerSubjectPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(CareerSubjectPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseCareerSubjectPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCareerSubjectPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     CareerSubject
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = CareerSubjectPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return CareerSubjectPeer::populateObjects(CareerSubjectPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCareerSubjectPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseCareerSubjectPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(CareerSubjectPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			CareerSubjectPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      CareerSubject $value A CareerSubject object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(CareerSubject $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A CareerSubject object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof CareerSubject) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or CareerSubject object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     CareerSubject Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = CareerSubjectPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = CareerSubjectPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = CareerSubjectPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				CareerSubjectPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related Career table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinCareer(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(CareerSubjectPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CareerSubjectPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CareerSubjectPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(CareerSubjectPeer::CAREER_ID,), array(CareerPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseCareerSubjectPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCareerSubjectPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Subject table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinSubject(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(CareerSubjectPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CareerSubjectPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CareerSubjectPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(CareerSubjectPeer::SUBJECT_ID,), array(SubjectPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseCareerSubjectPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCareerSubjectPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Orientation table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinOrientation(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(CareerSubjectPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CareerSubjectPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CareerSubjectPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(CareerSubjectPeer::ORIENTATION_ID,), array(OrientationPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseCareerSubjectPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCareerSubjectPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related SubOrientation table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinSubOrientation(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(CareerSubjectPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CareerSubjectPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CareerSubjectPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(CareerSubjectPeer::SUB_ORIENTATION_ID,), array(SubOrientationPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseCareerSubjectPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCareerSubjectPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of CareerSubject objects pre-filled with their Career objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of CareerSubject objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinCareer(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseCareerSubjectPeer:doSelectJoin:doSelectJoin') as $callable)
    {
      call_user_func($callable, 'BaseCareerSubjectPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CareerSubjectPeer::addSelectColumns($c);
		$startcol = (CareerSubjectPeer::NUM_COLUMNS - CareerSubjectPeer::NUM_LAZY_LOAD_COLUMNS);
		CareerPeer::addSelectColumns($c);

		$c->addJoin(array(CareerSubjectPeer::CAREER_ID,), array(CareerPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CareerSubjectPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CareerSubjectPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = CareerSubjectPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CareerSubjectPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = CareerPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = CareerPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = CareerPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					CareerPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (CareerSubject) to $obj2 (Career)
				$obj2->addCareerSubject($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of CareerSubject objects pre-filled with their Subject objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of CareerSubject objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinSubject(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CareerSubjectPeer::addSelectColumns($c);
		$startcol = (CareerSubjectPeer::NUM_COLUMNS - CareerSubjectPeer::NUM_LAZY_LOAD_COLUMNS);
		SubjectPeer::addSelectColumns($c);

		$c->addJoin(array(CareerSubjectPeer::SUBJECT_ID,), array(SubjectPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CareerSubjectPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CareerSubjectPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = CareerSubjectPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CareerSubjectPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = SubjectPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = SubjectPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = SubjectPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					SubjectPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (CareerSubject) to $obj2 (Subject)
				$obj2->addCareerSubject($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of CareerSubject objects pre-filled with their Orientation objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of CareerSubject objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinOrientation(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CareerSubjectPeer::addSelectColumns($c);
		$startcol = (CareerSubjectPeer::NUM_COLUMNS - CareerSubjectPeer::NUM_LAZY_LOAD_COLUMNS);
		OrientationPeer::addSelectColumns($c);

		$c->addJoin(array(CareerSubjectPeer::ORIENTATION_ID,), array(OrientationPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CareerSubjectPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CareerSubjectPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = CareerSubjectPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CareerSubjectPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = OrientationPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = OrientationPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = OrientationPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					OrientationPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (CareerSubject) to $obj2 (Orientation)
				$obj2->addCareerSubject($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of CareerSubject objects pre-filled with their SubOrientation objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of CareerSubject objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinSubOrientation(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CareerSubjectPeer::addSelectColumns($c);
		$startcol = (CareerSubjectPeer::NUM_COLUMNS - CareerSubjectPeer::NUM_LAZY_LOAD_COLUMNS);
		SubOrientationPeer::addSelectColumns($c);

		$c->addJoin(array(CareerSubjectPeer::SUB_ORIENTATION_ID,), array(SubOrientationPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CareerSubjectPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CareerSubjectPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = CareerSubjectPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CareerSubjectPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = SubOrientationPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = SubOrientationPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = SubOrientationPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					SubOrientationPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (CareerSubject) to $obj2 (SubOrientation)
				$obj2->addCareerSubject($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(CareerSubjectPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CareerSubjectPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CareerSubjectPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(CareerSubjectPeer::CAREER_ID,), array(CareerPeer::ID,), $join_behavior);
		$criteria->addJoin(array(CareerSubjectPeer::SUBJECT_ID,), array(SubjectPeer::ID,), $join_behavior);
		$criteria->addJoin(array(CareerSubjectPeer::ORIENTATION_ID,), array(OrientationPeer::ID,), $join_behavior);
		$criteria->addJoin(array(CareerSubjectPeer::SUB_ORIENTATION_ID,), array(SubOrientationPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseCareerSubjectPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCareerSubjectPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of CareerSubject objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of CareerSubject objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseCareerSubjectPeer:doSelectJoinAll:doSelectJoinAll') as $callable)
    {
      call_user_func($callable, 'BaseCareerSubjectPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CareerSubjectPeer::addSelectColumns($c);
		$startcol2 = (CareerSubjectPeer::NUM_COLUMNS - CareerSubjectPeer::NUM_LAZY_LOAD_COLUMNS);

		CareerPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (CareerPeer::NUM_COLUMNS - CareerPeer::NUM_LAZY_LOAD_COLUMNS);

		SubjectPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (SubjectPeer::NUM_COLUMNS - SubjectPeer::NUM_LAZY_LOAD_COLUMNS);

		OrientationPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (OrientationPeer::NUM_COLUMNS - OrientationPeer::NUM_LAZY_LOAD_COLUMNS);

		SubOrientationPeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (SubOrientationPeer::NUM_COLUMNS - SubOrientationPeer::NUM_LAZY_LOAD_COLUMNS);

		$c->addJoin(array(CareerSubjectPeer::CAREER_ID,), array(CareerPeer::ID,), $join_behavior);
		$c->addJoin(array(CareerSubjectPeer::SUBJECT_ID,), array(SubjectPeer::ID,), $join_behavior);
		$c->addJoin(array(CareerSubjectPeer::ORIENTATION_ID,), array(OrientationPeer::ID,), $join_behavior);
		$c->addJoin(array(CareerSubjectPeer::SUB_ORIENTATION_ID,), array(SubOrientationPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CareerSubjectPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CareerSubjectPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = CareerSubjectPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CareerSubjectPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined Career rows

			$key2 = CareerPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = CareerPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = CareerPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					CareerPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (CareerSubject) to the collection in $obj2 (Career)
				$obj2->addCareerSubject($obj1);
			} // if joined row not null

			// Add objects for joined Subject rows

			$key3 = SubjectPeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = SubjectPeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$omClass = SubjectPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					SubjectPeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (CareerSubject) to the collection in $obj3 (Subject)
				$obj3->addCareerSubject($obj1);
			} // if joined row not null

			// Add objects for joined Orientation rows

			$key4 = OrientationPeer::getPrimaryKeyHashFromRow($row, $startcol4);
			if ($key4 !== null) {
				$obj4 = OrientationPeer::getInstanceFromPool($key4);
				if (!$obj4) {

					$omClass = OrientationPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					OrientationPeer::addInstanceToPool($obj4, $key4);
				} // if obj4 loaded

				// Add the $obj1 (CareerSubject) to the collection in $obj4 (Orientation)
				$obj4->addCareerSubject($obj1);
			} // if joined row not null

			// Add objects for joined SubOrientation rows

			$key5 = SubOrientationPeer::getPrimaryKeyHashFromRow($row, $startcol5);
			if ($key5 !== null) {
				$obj5 = SubOrientationPeer::getInstanceFromPool($key5);
				if (!$obj5) {

					$omClass = SubOrientationPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					SubOrientationPeer::addInstanceToPool($obj5, $key5);
				} // if obj5 loaded

				// Add the $obj1 (CareerSubject) to the collection in $obj5 (SubOrientation)
				$obj5->addCareerSubject($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Career table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptCareer(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CareerSubjectPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CareerSubjectPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(CareerSubjectPeer::SUBJECT_ID,), array(SubjectPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CareerSubjectPeer::ORIENTATION_ID,), array(OrientationPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CareerSubjectPeer::SUB_ORIENTATION_ID,), array(SubOrientationPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseCareerSubjectPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCareerSubjectPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Subject table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptSubject(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CareerSubjectPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CareerSubjectPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(CareerSubjectPeer::CAREER_ID,), array(CareerPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CareerSubjectPeer::ORIENTATION_ID,), array(OrientationPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CareerSubjectPeer::SUB_ORIENTATION_ID,), array(SubOrientationPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseCareerSubjectPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCareerSubjectPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Orientation table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptOrientation(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CareerSubjectPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CareerSubjectPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(CareerSubjectPeer::CAREER_ID,), array(CareerPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CareerSubjectPeer::SUBJECT_ID,), array(SubjectPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CareerSubjectPeer::SUB_ORIENTATION_ID,), array(SubOrientationPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseCareerSubjectPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCareerSubjectPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related SubOrientation table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptSubOrientation(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CareerSubjectPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CareerSubjectPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(CareerSubjectPeer::CAREER_ID,), array(CareerPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CareerSubjectPeer::SUBJECT_ID,), array(SubjectPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CareerSubjectPeer::ORIENTATION_ID,), array(OrientationPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseCareerSubjectPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCareerSubjectPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of CareerSubject objects pre-filled with all related objects except Career.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of CareerSubject objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptCareer(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseCareerSubjectPeer:doSelectJoinAllExcept:doSelectJoinAllExcept') as $callable)
    {
      call_user_func($callable, 'BaseCareerSubjectPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CareerSubjectPeer::addSelectColumns($c);
		$startcol2 = (CareerSubjectPeer::NUM_COLUMNS - CareerSubjectPeer::NUM_LAZY_LOAD_COLUMNS);

		SubjectPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (SubjectPeer::NUM_COLUMNS - SubjectPeer::NUM_LAZY_LOAD_COLUMNS);

		OrientationPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (OrientationPeer::NUM_COLUMNS - OrientationPeer::NUM_LAZY_LOAD_COLUMNS);

		SubOrientationPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (SubOrientationPeer::NUM_COLUMNS - SubOrientationPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(CareerSubjectPeer::SUBJECT_ID,), array(SubjectPeer::ID,), $join_behavior);
				$c->addJoin(array(CareerSubjectPeer::ORIENTATION_ID,), array(OrientationPeer::ID,), $join_behavior);
				$c->addJoin(array(CareerSubjectPeer::SUB_ORIENTATION_ID,), array(SubOrientationPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CareerSubjectPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CareerSubjectPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = CareerSubjectPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CareerSubjectPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Subject rows

				$key2 = SubjectPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = SubjectPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = SubjectPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					SubjectPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (CareerSubject) to the collection in $obj2 (Subject)
				$obj2->addCareerSubject($obj1);

			} // if joined row is not null

				// Add objects for joined Orientation rows

				$key3 = OrientationPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = OrientationPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = OrientationPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					OrientationPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (CareerSubject) to the collection in $obj3 (Orientation)
				$obj3->addCareerSubject($obj1);

			} // if joined row is not null

				// Add objects for joined SubOrientation rows

				$key4 = SubOrientationPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = SubOrientationPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = SubOrientationPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					SubOrientationPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (CareerSubject) to the collection in $obj4 (SubOrientation)
				$obj4->addCareerSubject($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of CareerSubject objects pre-filled with all related objects except Subject.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of CareerSubject objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptSubject(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CareerSubjectPeer::addSelectColumns($c);
		$startcol2 = (CareerSubjectPeer::NUM_COLUMNS - CareerSubjectPeer::NUM_LAZY_LOAD_COLUMNS);

		CareerPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (CareerPeer::NUM_COLUMNS - CareerPeer::NUM_LAZY_LOAD_COLUMNS);

		OrientationPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (OrientationPeer::NUM_COLUMNS - OrientationPeer::NUM_LAZY_LOAD_COLUMNS);

		SubOrientationPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (SubOrientationPeer::NUM_COLUMNS - SubOrientationPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(CareerSubjectPeer::CAREER_ID,), array(CareerPeer::ID,), $join_behavior);
				$c->addJoin(array(CareerSubjectPeer::ORIENTATION_ID,), array(OrientationPeer::ID,), $join_behavior);
				$c->addJoin(array(CareerSubjectPeer::SUB_ORIENTATION_ID,), array(SubOrientationPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CareerSubjectPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CareerSubjectPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = CareerSubjectPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CareerSubjectPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Career rows

				$key2 = CareerPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = CareerPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = CareerPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					CareerPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (CareerSubject) to the collection in $obj2 (Career)
				$obj2->addCareerSubject($obj1);

			} // if joined row is not null

				// Add objects for joined Orientation rows

				$key3 = OrientationPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = OrientationPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = OrientationPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					OrientationPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (CareerSubject) to the collection in $obj3 (Orientation)
				$obj3->addCareerSubject($obj1);

			} // if joined row is not null

				// Add objects for joined SubOrientation rows

				$key4 = SubOrientationPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = SubOrientationPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = SubOrientationPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					SubOrientationPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (CareerSubject) to the collection in $obj4 (SubOrientation)
				$obj4->addCareerSubject($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of CareerSubject objects pre-filled with all related objects except Orientation.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of CareerSubject objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptOrientation(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CareerSubjectPeer::addSelectColumns($c);
		$startcol2 = (CareerSubjectPeer::NUM_COLUMNS - CareerSubjectPeer::NUM_LAZY_LOAD_COLUMNS);

		CareerPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (CareerPeer::NUM_COLUMNS - CareerPeer::NUM_LAZY_LOAD_COLUMNS);

		SubjectPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (SubjectPeer::NUM_COLUMNS - SubjectPeer::NUM_LAZY_LOAD_COLUMNS);

		SubOrientationPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (SubOrientationPeer::NUM_COLUMNS - SubOrientationPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(CareerSubjectPeer::CAREER_ID,), array(CareerPeer::ID,), $join_behavior);
				$c->addJoin(array(CareerSubjectPeer::SUBJECT_ID,), array(SubjectPeer::ID,), $join_behavior);
				$c->addJoin(array(CareerSubjectPeer::SUB_ORIENTATION_ID,), array(SubOrientationPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CareerSubjectPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CareerSubjectPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = CareerSubjectPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CareerSubjectPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Career rows

				$key2 = CareerPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = CareerPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = CareerPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					CareerPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (CareerSubject) to the collection in $obj2 (Career)
				$obj2->addCareerSubject($obj1);

			} // if joined row is not null

				// Add objects for joined Subject rows

				$key3 = SubjectPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = SubjectPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = SubjectPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					SubjectPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (CareerSubject) to the collection in $obj3 (Subject)
				$obj3->addCareerSubject($obj1);

			} // if joined row is not null

				// Add objects for joined SubOrientation rows

				$key4 = SubOrientationPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = SubOrientationPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = SubOrientationPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					SubOrientationPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (CareerSubject) to the collection in $obj4 (SubOrientation)
				$obj4->addCareerSubject($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of CareerSubject objects pre-filled with all related objects except SubOrientation.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of CareerSubject objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptSubOrientation(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CareerSubjectPeer::addSelectColumns($c);
		$startcol2 = (CareerSubjectPeer::NUM_COLUMNS - CareerSubjectPeer::NUM_LAZY_LOAD_COLUMNS);

		CareerPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (CareerPeer::NUM_COLUMNS - CareerPeer::NUM_LAZY_LOAD_COLUMNS);

		SubjectPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (SubjectPeer::NUM_COLUMNS - SubjectPeer::NUM_LAZY_LOAD_COLUMNS);

		OrientationPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (OrientationPeer::NUM_COLUMNS - OrientationPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(CareerSubjectPeer::CAREER_ID,), array(CareerPeer::ID,), $join_behavior);
				$c->addJoin(array(CareerSubjectPeer::SUBJECT_ID,), array(SubjectPeer::ID,), $join_behavior);
				$c->addJoin(array(CareerSubjectPeer::ORIENTATION_ID,), array(OrientationPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CareerSubjectPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CareerSubjectPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = CareerSubjectPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CareerSubjectPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Career rows

				$key2 = CareerPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = CareerPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = CareerPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					CareerPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (CareerSubject) to the collection in $obj2 (Career)
				$obj2->addCareerSubject($obj1);

			} // if joined row is not null

				// Add objects for joined Subject rows

				$key3 = SubjectPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = SubjectPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = SubjectPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					SubjectPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (CareerSubject) to the collection in $obj3 (Subject)
				$obj3->addCareerSubject($obj1);

			} // if joined row is not null

				// Add objects for joined Orientation rows

				$key4 = OrientationPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = OrientationPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = OrientationPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					OrientationPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (CareerSubject) to the collection in $obj4 (Orientation)
				$obj4->addCareerSubject($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


  static public function getUniqueColumnNames()
  {
    return array(array('career_id', 'subject_id', 'year', 'orientation_id', 'sub_orientation_id'));
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return CareerSubjectPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a CareerSubject or Criteria object.
	 *
	 * @param      mixed $values Criteria or CareerSubject object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCareerSubjectPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseCareerSubjectPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(CareerSubjectPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from CareerSubject object
		}

		if ($criteria->containsKey(CareerSubjectPeer::ID) && $criteria->keyContainsValue(CareerSubjectPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.CareerSubjectPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseCareerSubjectPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseCareerSubjectPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a CareerSubject or Criteria object.
	 *
	 * @param      mixed $values Criteria or CareerSubject object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCareerSubjectPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseCareerSubjectPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(CareerSubjectPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(CareerSubjectPeer::ID);
			$selectCriteria->add(CareerSubjectPeer::ID, $criteria->remove(CareerSubjectPeer::ID), $comparison);

		} else { // $values is CareerSubject object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseCareerSubjectPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseCareerSubjectPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the career_subject table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CareerSubjectPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += CareerSubjectPeer::doOnDeleteCascade(new Criteria(CareerSubjectPeer::DATABASE_NAME), $con);
			$affectedRows += BasePeer::doDeleteAll(CareerSubjectPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a CareerSubject or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or CareerSubject object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(CareerSubjectPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			CareerSubjectPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof CareerSubject) {
			// invalidate the cache for this single object
			CareerSubjectPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(CareerSubjectPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				CareerSubjectPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += CareerSubjectPeer::doOnDeleteCascade($criteria, $con);
			
				// Because this db requires some delete cascade/set null emulation, we have to
				// clear the cached instance *after* the emulation has happened (since
				// instances get re-added by the select statement contained therein).
				if ($values instanceof Criteria) {
					CareerSubjectPeer::clearInstancePool();
				} else { // it's a PK or object
					CareerSubjectPeer::removeInstanceFromPool($values);
				}
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			// invalidate objects in CorrelativePeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			CorrelativePeer::clearInstancePool();

			// invalidate objects in CorrelativePeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			CorrelativePeer::clearInstancePool();

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * This is a method for emulating ON DELETE CASCADE for DBs that don't support this
	 * feature (like MySQL or SQLite).
	 *
	 * This method is not very speedy because it must perform a query first to get
	 * the implicated records and then perform the deletes by calling those Peer classes.
	 *
	 * This method should be used within a transaction if possible.
	 *
	 * @param      Criteria $criteria
	 * @param      PropelPDO $con
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	protected static function doOnDeleteCascade(Criteria $criteria, PropelPDO $con)
	{
		// initialize var to track total num of affected rows
		$affectedRows = 0;

		// first find the objects that are implicated by the $criteria
		$objects = CareerSubjectPeer::doSelect($criteria, $con);
		foreach ($objects as $obj) {


			// delete related Correlative objects
			$c = new Criteria(CorrelativePeer::DATABASE_NAME);
			
			$c->add(CorrelativePeer::CAREER_SUBJECT_ID, $obj->getId());
			$affectedRows += CorrelativePeer::doDelete($c, $con);

			// delete related Correlative objects
			$c = new Criteria(CorrelativePeer::DATABASE_NAME);
			
			$c->add(CorrelativePeer::CORRELATIVE_CAREER_SUBJECT_ID, $obj->getId());
			$affectedRows += CorrelativePeer::doDelete($c, $con);
		}
		return $affectedRows;
	}

	/**
	 * Validates all modified columns of given CareerSubject object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      CareerSubject $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(CareerSubject $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(CareerSubjectPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(CareerSubjectPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(CareerSubjectPeer::DATABASE_NAME, CareerSubjectPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        foreach ($res as $failed) {
            $col = CareerSubjectPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     CareerSubject
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = CareerSubjectPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(CareerSubjectPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(CareerSubjectPeer::DATABASE_NAME);
		$criteria->add(CareerSubjectPeer::ID, $pk);

		$v = CareerSubjectPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CareerSubjectPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(CareerSubjectPeer::DATABASE_NAME);
			$criteria->add(CareerSubjectPeer::ID, $pks, Criteria::IN);
			$objs = CareerSubjectPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseCareerSubjectPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the CareerSubjectPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the CareerSubjectPeer class:
//
// Propel::getDatabaseMap(CareerSubjectPeer::DATABASE_NAME)->addTableBuilder(CareerSubjectPeer::TABLE_NAME, CareerSubjectPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseCareerSubjectPeer::DATABASE_NAME)->addTableBuilder(BaseCareerSubjectPeer::TABLE_NAME, BaseCareerSubjectPeer::getMapBuilder());

