<?php

/**
 * Base static class for performing query and update operations on the 'subject_configuration' table.
 *
 * Configuración de las materias
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Aug 23 21:09:09 2018
 *
 * @package    lib.model.om
 */
abstract class BaseSubjectConfigurationPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'subject_configuration';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.SubjectConfiguration';

	/** The total number of columns. */
	const NUM_COLUMNS = 14;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'subject_configuration.ID';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'subject_configuration.CREATED_AT';

	/** the column name for the COURSE_MARKS field */
	const COURSE_MARKS = 'subject_configuration.COURSE_MARKS';

	/** the column name for the FINAL_EXAMINATION_REQUIRED field */
	const FINAL_EXAMINATION_REQUIRED = 'subject_configuration.FINAL_EXAMINATION_REQUIRED';

	/** the column name for the COURSE_REQUIRED field */
	const COURSE_REQUIRED = 'subject_configuration.COURSE_REQUIRED';

	/** the column name for the COURSE_MINIMUN_MARK field */
	const COURSE_MINIMUN_MARK = 'subject_configuration.COURSE_MINIMUN_MARK';

	/** the column name for the COURSE_EXAMINATION_COUNT field */
	const COURSE_EXAMINATION_COUNT = 'subject_configuration.COURSE_EXAMINATION_COUNT';

	/** the column name for the MAX_PREVIOUS field */
	const MAX_PREVIOUS = 'subject_configuration.MAX_PREVIOUS';

	/** the column name for the EVALUATION_METHOD field */
	const EVALUATION_METHOD = 'subject_configuration.EVALUATION_METHOD';

	/** the column name for the COURSE_TYPE field */
	const COURSE_TYPE = 'subject_configuration.COURSE_TYPE';

	/** the column name for the ATTENDANCE_TYPE field */
	const ATTENDANCE_TYPE = 'subject_configuration.ATTENDANCE_TYPE';

	/** the column name for the MAX_DISCIPLINARY_SANCTIONS field */
	const MAX_DISCIPLINARY_SANCTIONS = 'subject_configuration.MAX_DISCIPLINARY_SANCTIONS';

	/** the column name for the WHEN_DISAPPROVE_SHOW_STRING field */
	const WHEN_DISAPPROVE_SHOW_STRING = 'subject_configuration.WHEN_DISAPPROVE_SHOW_STRING';

	/** the column name for the NECESSARY_STUDENT_APPROVED_CAREER_SUBJECT_TO_SHOW_PROM_DEF field */
	const NECESSARY_STUDENT_APPROVED_CAREER_SUBJECT_TO_SHOW_PROM_DEF = 'subject_configuration.NECESSARY_STUDENT_APPROVED_CAREER_SUBJECT_TO_SHOW_PROM_DEF';

	/**
	 * An identiy map to hold any loaded instances of SubjectConfiguration objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array SubjectConfiguration[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'CreatedAt', 'CourseMarks', 'FinalExaminationRequired', 'CourseRequired', 'CourseMinimunMark', 'CourseExaminationCount', 'MaxPrevious', 'EvaluationMethod', 'CourseType', 'AttendanceType', 'MaxDisciplinarySanctions', 'WhenDisapproveShowString', 'NecessaryStudentApprovedCareerSubjectToShowPromDef', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'createdAt', 'courseMarks', 'finalExaminationRequired', 'courseRequired', 'courseMinimunMark', 'courseExaminationCount', 'maxPrevious', 'evaluationMethod', 'courseType', 'attendanceType', 'maxDisciplinarySanctions', 'whenDisapproveShowString', 'necessaryStudentApprovedCareerSubjectToShowPromDef', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::CREATED_AT, self::COURSE_MARKS, self::FINAL_EXAMINATION_REQUIRED, self::COURSE_REQUIRED, self::COURSE_MINIMUN_MARK, self::COURSE_EXAMINATION_COUNT, self::MAX_PREVIOUS, self::EVALUATION_METHOD, self::COURSE_TYPE, self::ATTENDANCE_TYPE, self::MAX_DISCIPLINARY_SANCTIONS, self::WHEN_DISAPPROVE_SHOW_STRING, self::NECESSARY_STUDENT_APPROVED_CAREER_SUBJECT_TO_SHOW_PROM_DEF, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'created_at', 'course_marks', 'final_examination_required', 'course_required', 'course_minimun_mark', 'course_examination_count', 'max_previous', 'evaluation_method', 'course_type', 'attendance_type', 'max_disciplinary_sanctions', 'when_disapprove_show_string', 'necessary_student_approved_career_subject_to_show_prom_def', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'CreatedAt' => 1, 'CourseMarks' => 2, 'FinalExaminationRequired' => 3, 'CourseRequired' => 4, 'CourseMinimunMark' => 5, 'CourseExaminationCount' => 6, 'MaxPrevious' => 7, 'EvaluationMethod' => 8, 'CourseType' => 9, 'AttendanceType' => 10, 'MaxDisciplinarySanctions' => 11, 'WhenDisapproveShowString' => 12, 'NecessaryStudentApprovedCareerSubjectToShowPromDef' => 13, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'createdAt' => 1, 'courseMarks' => 2, 'finalExaminationRequired' => 3, 'courseRequired' => 4, 'courseMinimunMark' => 5, 'courseExaminationCount' => 6, 'maxPrevious' => 7, 'evaluationMethod' => 8, 'courseType' => 9, 'attendanceType' => 10, 'maxDisciplinarySanctions' => 11, 'whenDisapproveShowString' => 12, 'necessaryStudentApprovedCareerSubjectToShowPromDef' => 13, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::CREATED_AT => 1, self::COURSE_MARKS => 2, self::FINAL_EXAMINATION_REQUIRED => 3, self::COURSE_REQUIRED => 4, self::COURSE_MINIMUN_MARK => 5, self::COURSE_EXAMINATION_COUNT => 6, self::MAX_PREVIOUS => 7, self::EVALUATION_METHOD => 8, self::COURSE_TYPE => 9, self::ATTENDANCE_TYPE => 10, self::MAX_DISCIPLINARY_SANCTIONS => 11, self::WHEN_DISAPPROVE_SHOW_STRING => 12, self::NECESSARY_STUDENT_APPROVED_CAREER_SUBJECT_TO_SHOW_PROM_DEF => 13, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'created_at' => 1, 'course_marks' => 2, 'final_examination_required' => 3, 'course_required' => 4, 'course_minimun_mark' => 5, 'course_examination_count' => 6, 'max_previous' => 7, 'evaluation_method' => 8, 'course_type' => 9, 'attendance_type' => 10, 'max_disciplinary_sanctions' => 11, 'when_disapprove_show_string' => 12, 'necessary_student_approved_career_subject_to_show_prom_def' => 13, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new SubjectConfigurationMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. SubjectConfigurationPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(SubjectConfigurationPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(SubjectConfigurationPeer::ID);

		$criteria->addSelectColumn(SubjectConfigurationPeer::CREATED_AT);

		$criteria->addSelectColumn(SubjectConfigurationPeer::COURSE_MARKS);

		$criteria->addSelectColumn(SubjectConfigurationPeer::FINAL_EXAMINATION_REQUIRED);

		$criteria->addSelectColumn(SubjectConfigurationPeer::COURSE_REQUIRED);

		$criteria->addSelectColumn(SubjectConfigurationPeer::COURSE_MINIMUN_MARK);

		$criteria->addSelectColumn(SubjectConfigurationPeer::COURSE_EXAMINATION_COUNT);

		$criteria->addSelectColumn(SubjectConfigurationPeer::MAX_PREVIOUS);

		$criteria->addSelectColumn(SubjectConfigurationPeer::EVALUATION_METHOD);

		$criteria->addSelectColumn(SubjectConfigurationPeer::COURSE_TYPE);

		$criteria->addSelectColumn(SubjectConfigurationPeer::ATTENDANCE_TYPE);

		$criteria->addSelectColumn(SubjectConfigurationPeer::MAX_DISCIPLINARY_SANCTIONS);

		$criteria->addSelectColumn(SubjectConfigurationPeer::WHEN_DISAPPROVE_SHOW_STRING);

		$criteria->addSelectColumn(SubjectConfigurationPeer::NECESSARY_STUDENT_APPROVED_CAREER_SUBJECT_TO_SHOW_PROM_DEF);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(SubjectConfigurationPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			SubjectConfigurationPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(SubjectConfigurationPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseSubjectConfigurationPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseSubjectConfigurationPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     SubjectConfiguration
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = SubjectConfigurationPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return SubjectConfigurationPeer::populateObjects(SubjectConfigurationPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseSubjectConfigurationPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseSubjectConfigurationPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(SubjectConfigurationPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			SubjectConfigurationPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      SubjectConfiguration $value A SubjectConfiguration object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(SubjectConfiguration $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A SubjectConfiguration object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof SubjectConfiguration) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or SubjectConfiguration object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     SubjectConfiguration Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = SubjectConfigurationPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = SubjectConfigurationPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = SubjectConfigurationPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				SubjectConfigurationPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return SubjectConfigurationPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a SubjectConfiguration or Criteria object.
	 *
	 * @param      mixed $values Criteria or SubjectConfiguration object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseSubjectConfigurationPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseSubjectConfigurationPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(SubjectConfigurationPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from SubjectConfiguration object
		}

		if ($criteria->containsKey(SubjectConfigurationPeer::ID) && $criteria->keyContainsValue(SubjectConfigurationPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.SubjectConfigurationPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseSubjectConfigurationPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseSubjectConfigurationPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a SubjectConfiguration or Criteria object.
	 *
	 * @param      mixed $values Criteria or SubjectConfiguration object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseSubjectConfigurationPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseSubjectConfigurationPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(SubjectConfigurationPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(SubjectConfigurationPeer::ID);
			$selectCriteria->add(SubjectConfigurationPeer::ID, $criteria->remove(SubjectConfigurationPeer::ID), $comparison);

		} else { // $values is SubjectConfiguration object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseSubjectConfigurationPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseSubjectConfigurationPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the subject_configuration table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(SubjectConfigurationPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += SubjectConfigurationPeer::doOnDeleteCascade(new Criteria(SubjectConfigurationPeer::DATABASE_NAME), $con);
			SubjectConfigurationPeer::doOnDeleteSetNull(new Criteria(SubjectConfigurationPeer::DATABASE_NAME), $con);
			$affectedRows += BasePeer::doDeleteAll(SubjectConfigurationPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a SubjectConfiguration or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or SubjectConfiguration object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(SubjectConfigurationPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			SubjectConfigurationPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof SubjectConfiguration) {
			// invalidate the cache for this single object
			SubjectConfigurationPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(SubjectConfigurationPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				SubjectConfigurationPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += SubjectConfigurationPeer::doOnDeleteCascade($criteria, $con);
			SubjectConfigurationPeer::doOnDeleteSetNull($criteria, $con);
			
				// Because this db requires some delete cascade/set null emulation, we have to
				// clear the cached instance *after* the emulation has happened (since
				// instances get re-added by the select statement contained therein).
				if ($values instanceof Criteria) {
					SubjectConfigurationPeer::clearInstancePool();
				} else { // it's a PK or object
					SubjectConfigurationPeer::removeInstanceFromPool($values);
				}
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			// invalidate objects in CareerYearConfigurationPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			CareerYearConfigurationPeer::clearInstancePool();

			// invalidate objects in CareerSubjectSchoolYearPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			CareerSubjectSchoolYearPeer::clearInstancePool();

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * This is a method for emulating ON DELETE CASCADE for DBs that don't support this
	 * feature (like MySQL or SQLite).
	 *
	 * This method is not very speedy because it must perform a query first to get
	 * the implicated records and then perform the deletes by calling those Peer classes.
	 *
	 * This method should be used within a transaction if possible.
	 *
	 * @param      Criteria $criteria
	 * @param      PropelPDO $con
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	protected static function doOnDeleteCascade(Criteria $criteria, PropelPDO $con)
	{
		// initialize var to track total num of affected rows
		$affectedRows = 0;

		// first find the objects that are implicated by the $criteria
		$objects = SubjectConfigurationPeer::doSelect($criteria, $con);
		foreach ($objects as $obj) {


			// delete related CareerYearConfiguration objects
			$c = new Criteria(CareerYearConfigurationPeer::DATABASE_NAME);
			
			$c->add(CareerYearConfigurationPeer::SUBJECT_CONFIGURATION_ID, $obj->getId());
			$affectedRows += CareerYearConfigurationPeer::doDelete($c, $con);
		}
		return $affectedRows;
	}

	/**
	 * This is a method for emulating ON DELETE SET NULL DBs that don't support this
	 * feature (like MySQL or SQLite).
	 *
	 * This method is not very speedy because it must perform a query first to get
	 * the implicated records and then perform the deletes by calling those Peer classes.
	 *
	 * This method should be used within a transaction if possible.
	 *
	 * @param      Criteria $criteria
	 * @param      PropelPDO $con
	 * @return     void
	 */
	protected static function doOnDeleteSetNull(Criteria $criteria, PropelPDO $con)
	{

		// first find the objects that are implicated by the $criteria
		$objects = SubjectConfigurationPeer::doSelect($criteria, $con);
		foreach ($objects as $obj) {

			// set fkey col in related CareerSubjectSchoolYear rows to NULL
			$selectCriteria = new Criteria(SubjectConfigurationPeer::DATABASE_NAME);
			$updateValues = new Criteria(SubjectConfigurationPeer::DATABASE_NAME);
			$selectCriteria->add(CareerSubjectSchoolYearPeer::SUBJECT_CONFIGURATION_ID, $obj->getId());
			$updateValues->add(CareerSubjectSchoolYearPeer::SUBJECT_CONFIGURATION_ID, null);

					BasePeer::doUpdate($selectCriteria, $updateValues, $con); // use BasePeer because generated Peer doUpdate() methods only update using pkey

		}
	}

	/**
	 * Validates all modified columns of given SubjectConfiguration object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      SubjectConfiguration $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(SubjectConfiguration $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(SubjectConfigurationPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(SubjectConfigurationPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(SubjectConfigurationPeer::DATABASE_NAME, SubjectConfigurationPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        foreach ($res as $failed) {
            $col = SubjectConfigurationPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     SubjectConfiguration
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = SubjectConfigurationPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(SubjectConfigurationPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(SubjectConfigurationPeer::DATABASE_NAME);
		$criteria->add(SubjectConfigurationPeer::ID, $pk);

		$v = SubjectConfigurationPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(SubjectConfigurationPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(SubjectConfigurationPeer::DATABASE_NAME);
			$criteria->add(SubjectConfigurationPeer::ID, $pks, Criteria::IN);
			$objs = SubjectConfigurationPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseSubjectConfigurationPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the SubjectConfigurationPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the SubjectConfigurationPeer class:
//
// Propel::getDatabaseMap(SubjectConfigurationPeer::DATABASE_NAME)->addTableBuilder(SubjectConfigurationPeer::TABLE_NAME, SubjectConfigurationPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseSubjectConfigurationPeer::DATABASE_NAME)->addTableBuilder(BaseSubjectConfigurationPeer::TABLE_NAME, BaseSubjectConfigurationPeer::getMapBuilder());

