<?php

/**
 * Base static class for performing query and update operations on the 'student_free' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Aug 23 21:09:09 2018
 *
 * @package    lib.model.om
 */
abstract class BaseStudentFreePeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'student_free';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.StudentFree';

	/** The total number of columns. */
	const NUM_COLUMNS = 6;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the STUDENT_ID field */
	const STUDENT_ID = 'student_free.STUDENT_ID';

	/** the column name for the CAREER_SCHOOL_YEAR_PERIOD_ID field */
	const CAREER_SCHOOL_YEAR_PERIOD_ID = 'student_free.CAREER_SCHOOL_YEAR_PERIOD_ID';

	/** the column name for the CAREER_SCHOOL_YEAR_ID field */
	const CAREER_SCHOOL_YEAR_ID = 'student_free.CAREER_SCHOOL_YEAR_ID';

	/** the column name for the COURSE_SUBJECT_ID field */
	const COURSE_SUBJECT_ID = 'student_free.COURSE_SUBJECT_ID';

	/** the column name for the IS_FREE field */
	const IS_FREE = 'student_free.IS_FREE';

	/** the column name for the ID field */
	const ID = 'student_free.ID';

	/**
	 * An identiy map to hold any loaded instances of StudentFree objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array StudentFree[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('StudentId', 'CareerSchoolYearPeriodId', 'CareerSchoolYearId', 'CourseSubjectId', 'IsFree', 'Id', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('studentId', 'careerSchoolYearPeriodId', 'careerSchoolYearId', 'courseSubjectId', 'isFree', 'id', ),
		BasePeer::TYPE_COLNAME => array (self::STUDENT_ID, self::CAREER_SCHOOL_YEAR_PERIOD_ID, self::CAREER_SCHOOL_YEAR_ID, self::COURSE_SUBJECT_ID, self::IS_FREE, self::ID, ),
		BasePeer::TYPE_FIELDNAME => array ('student_id', 'career_school_year_period_id', 'career_school_year_id', 'course_subject_id', 'is_free', 'id', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('StudentId' => 0, 'CareerSchoolYearPeriodId' => 1, 'CareerSchoolYearId' => 2, 'CourseSubjectId' => 3, 'IsFree' => 4, 'Id' => 5, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('studentId' => 0, 'careerSchoolYearPeriodId' => 1, 'careerSchoolYearId' => 2, 'courseSubjectId' => 3, 'isFree' => 4, 'id' => 5, ),
		BasePeer::TYPE_COLNAME => array (self::STUDENT_ID => 0, self::CAREER_SCHOOL_YEAR_PERIOD_ID => 1, self::CAREER_SCHOOL_YEAR_ID => 2, self::COURSE_SUBJECT_ID => 3, self::IS_FREE => 4, self::ID => 5, ),
		BasePeer::TYPE_FIELDNAME => array ('student_id' => 0, 'career_school_year_period_id' => 1, 'career_school_year_id' => 2, 'course_subject_id' => 3, 'is_free' => 4, 'id' => 5, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new StudentFreeMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. StudentFreePeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(StudentFreePeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(StudentFreePeer::STUDENT_ID);

		$criteria->addSelectColumn(StudentFreePeer::CAREER_SCHOOL_YEAR_PERIOD_ID);

		$criteria->addSelectColumn(StudentFreePeer::CAREER_SCHOOL_YEAR_ID);

		$criteria->addSelectColumn(StudentFreePeer::COURSE_SUBJECT_ID);

		$criteria->addSelectColumn(StudentFreePeer::IS_FREE);

		$criteria->addSelectColumn(StudentFreePeer::ID);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(StudentFreePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			StudentFreePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(StudentFreePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseStudentFreePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseStudentFreePeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     StudentFree
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = StudentFreePeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return StudentFreePeer::populateObjects(StudentFreePeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseStudentFreePeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseStudentFreePeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(StudentFreePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			StudentFreePeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      StudentFree $value A StudentFree object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(StudentFree $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A StudentFree object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof StudentFree) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or StudentFree object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     StudentFree Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 5] === null) {
			return null;
		}
		return (string) $row[$startcol + 5];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = StudentFreePeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = StudentFreePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = StudentFreePeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				StudentFreePeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related Student table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinStudent(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(StudentFreePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			StudentFreePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(StudentFreePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(StudentFreePeer::STUDENT_ID,), array(StudentPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseStudentFreePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseStudentFreePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related CareerSchoolYearPeriod table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinCareerSchoolYearPeriod(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(StudentFreePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			StudentFreePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(StudentFreePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_PERIOD_ID,), array(CareerSchoolYearPeriodPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseStudentFreePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseStudentFreePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related CareerSchoolYear table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinCareerSchoolYear(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(StudentFreePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			StudentFreePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(StudentFreePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_ID,), array(CareerSchoolYearPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseStudentFreePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseStudentFreePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related CourseSubject table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinCourseSubject(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(StudentFreePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			StudentFreePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(StudentFreePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(StudentFreePeer::COURSE_SUBJECT_ID,), array(CourseSubjectPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseStudentFreePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseStudentFreePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of StudentFree objects pre-filled with their Student objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of StudentFree objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinStudent(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseStudentFreePeer:doSelectJoin:doSelectJoin') as $callable)
    {
      call_user_func($callable, 'BaseStudentFreePeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		StudentFreePeer::addSelectColumns($c);
		$startcol = (StudentFreePeer::NUM_COLUMNS - StudentFreePeer::NUM_LAZY_LOAD_COLUMNS);
		StudentPeer::addSelectColumns($c);

		$c->addJoin(array(StudentFreePeer::STUDENT_ID,), array(StudentPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = StudentFreePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = StudentFreePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = StudentFreePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				StudentFreePeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = StudentPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = StudentPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = StudentPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					StudentPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (StudentFree) to $obj2 (Student)
				$obj2->addStudentFree($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of StudentFree objects pre-filled with their CareerSchoolYearPeriod objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of StudentFree objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinCareerSchoolYearPeriod(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		StudentFreePeer::addSelectColumns($c);
		$startcol = (StudentFreePeer::NUM_COLUMNS - StudentFreePeer::NUM_LAZY_LOAD_COLUMNS);
		CareerSchoolYearPeriodPeer::addSelectColumns($c);

		$c->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_PERIOD_ID,), array(CareerSchoolYearPeriodPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = StudentFreePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = StudentFreePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = StudentFreePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				StudentFreePeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = CareerSchoolYearPeriodPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = CareerSchoolYearPeriodPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = CareerSchoolYearPeriodPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					CareerSchoolYearPeriodPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (StudentFree) to $obj2 (CareerSchoolYearPeriod)
				$obj2->addStudentFree($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of StudentFree objects pre-filled with their CareerSchoolYear objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of StudentFree objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinCareerSchoolYear(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		StudentFreePeer::addSelectColumns($c);
		$startcol = (StudentFreePeer::NUM_COLUMNS - StudentFreePeer::NUM_LAZY_LOAD_COLUMNS);
		CareerSchoolYearPeer::addSelectColumns($c);

		$c->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_ID,), array(CareerSchoolYearPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = StudentFreePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = StudentFreePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = StudentFreePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				StudentFreePeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = CareerSchoolYearPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = CareerSchoolYearPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = CareerSchoolYearPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					CareerSchoolYearPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (StudentFree) to $obj2 (CareerSchoolYear)
				$obj2->addStudentFree($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of StudentFree objects pre-filled with their CourseSubject objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of StudentFree objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinCourseSubject(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		StudentFreePeer::addSelectColumns($c);
		$startcol = (StudentFreePeer::NUM_COLUMNS - StudentFreePeer::NUM_LAZY_LOAD_COLUMNS);
		CourseSubjectPeer::addSelectColumns($c);

		$c->addJoin(array(StudentFreePeer::COURSE_SUBJECT_ID,), array(CourseSubjectPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = StudentFreePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = StudentFreePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = StudentFreePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				StudentFreePeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = CourseSubjectPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = CourseSubjectPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = CourseSubjectPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					CourseSubjectPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (StudentFree) to $obj2 (CourseSubject)
				$obj2->addStudentFree($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(StudentFreePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			StudentFreePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(StudentFreePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(StudentFreePeer::STUDENT_ID,), array(StudentPeer::ID,), $join_behavior);
		$criteria->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_PERIOD_ID,), array(CareerSchoolYearPeriodPeer::ID,), $join_behavior);
		$criteria->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_ID,), array(CareerSchoolYearPeer::ID,), $join_behavior);
		$criteria->addJoin(array(StudentFreePeer::COURSE_SUBJECT_ID,), array(CourseSubjectPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseStudentFreePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseStudentFreePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of StudentFree objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of StudentFree objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseStudentFreePeer:doSelectJoinAll:doSelectJoinAll') as $callable)
    {
      call_user_func($callable, 'BaseStudentFreePeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		StudentFreePeer::addSelectColumns($c);
		$startcol2 = (StudentFreePeer::NUM_COLUMNS - StudentFreePeer::NUM_LAZY_LOAD_COLUMNS);

		StudentPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (StudentPeer::NUM_COLUMNS - StudentPeer::NUM_LAZY_LOAD_COLUMNS);

		CareerSchoolYearPeriodPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (CareerSchoolYearPeriodPeer::NUM_COLUMNS - CareerSchoolYearPeriodPeer::NUM_LAZY_LOAD_COLUMNS);

		CareerSchoolYearPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (CareerSchoolYearPeer::NUM_COLUMNS - CareerSchoolYearPeer::NUM_LAZY_LOAD_COLUMNS);

		CourseSubjectPeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (CourseSubjectPeer::NUM_COLUMNS - CourseSubjectPeer::NUM_LAZY_LOAD_COLUMNS);

		$c->addJoin(array(StudentFreePeer::STUDENT_ID,), array(StudentPeer::ID,), $join_behavior);
		$c->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_PERIOD_ID,), array(CareerSchoolYearPeriodPeer::ID,), $join_behavior);
		$c->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_ID,), array(CareerSchoolYearPeer::ID,), $join_behavior);
		$c->addJoin(array(StudentFreePeer::COURSE_SUBJECT_ID,), array(CourseSubjectPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = StudentFreePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = StudentFreePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = StudentFreePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				StudentFreePeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined Student rows

			$key2 = StudentPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = StudentPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = StudentPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					StudentPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (StudentFree) to the collection in $obj2 (Student)
				$obj2->addStudentFree($obj1);
			} // if joined row not null

			// Add objects for joined CareerSchoolYearPeriod rows

			$key3 = CareerSchoolYearPeriodPeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = CareerSchoolYearPeriodPeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$omClass = CareerSchoolYearPeriodPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					CareerSchoolYearPeriodPeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (StudentFree) to the collection in $obj3 (CareerSchoolYearPeriod)
				$obj3->addStudentFree($obj1);
			} // if joined row not null

			// Add objects for joined CareerSchoolYear rows

			$key4 = CareerSchoolYearPeer::getPrimaryKeyHashFromRow($row, $startcol4);
			if ($key4 !== null) {
				$obj4 = CareerSchoolYearPeer::getInstanceFromPool($key4);
				if (!$obj4) {

					$omClass = CareerSchoolYearPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					CareerSchoolYearPeer::addInstanceToPool($obj4, $key4);
				} // if obj4 loaded

				// Add the $obj1 (StudentFree) to the collection in $obj4 (CareerSchoolYear)
				$obj4->addStudentFree($obj1);
			} // if joined row not null

			// Add objects for joined CourseSubject rows

			$key5 = CourseSubjectPeer::getPrimaryKeyHashFromRow($row, $startcol5);
			if ($key5 !== null) {
				$obj5 = CourseSubjectPeer::getInstanceFromPool($key5);
				if (!$obj5) {

					$omClass = CourseSubjectPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					CourseSubjectPeer::addInstanceToPool($obj5, $key5);
				} // if obj5 loaded

				// Add the $obj1 (StudentFree) to the collection in $obj5 (CourseSubject)
				$obj5->addStudentFree($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Student table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptStudent(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			StudentFreePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(StudentFreePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_PERIOD_ID,), array(CareerSchoolYearPeriodPeer::ID,), $join_behavior);
				$criteria->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_ID,), array(CareerSchoolYearPeer::ID,), $join_behavior);
				$criteria->addJoin(array(StudentFreePeer::COURSE_SUBJECT_ID,), array(CourseSubjectPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseStudentFreePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseStudentFreePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related CareerSchoolYearPeriod table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptCareerSchoolYearPeriod(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			StudentFreePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(StudentFreePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(StudentFreePeer::STUDENT_ID,), array(StudentPeer::ID,), $join_behavior);
				$criteria->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_ID,), array(CareerSchoolYearPeer::ID,), $join_behavior);
				$criteria->addJoin(array(StudentFreePeer::COURSE_SUBJECT_ID,), array(CourseSubjectPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseStudentFreePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseStudentFreePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related CareerSchoolYear table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptCareerSchoolYear(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			StudentFreePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(StudentFreePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(StudentFreePeer::STUDENT_ID,), array(StudentPeer::ID,), $join_behavior);
				$criteria->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_PERIOD_ID,), array(CareerSchoolYearPeriodPeer::ID,), $join_behavior);
				$criteria->addJoin(array(StudentFreePeer::COURSE_SUBJECT_ID,), array(CourseSubjectPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseStudentFreePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseStudentFreePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related CourseSubject table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptCourseSubject(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			StudentFreePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(StudentFreePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(StudentFreePeer::STUDENT_ID,), array(StudentPeer::ID,), $join_behavior);
				$criteria->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_PERIOD_ID,), array(CareerSchoolYearPeriodPeer::ID,), $join_behavior);
				$criteria->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_ID,), array(CareerSchoolYearPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseStudentFreePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseStudentFreePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of StudentFree objects pre-filled with all related objects except Student.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of StudentFree objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptStudent(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseStudentFreePeer:doSelectJoinAllExcept:doSelectJoinAllExcept') as $callable)
    {
      call_user_func($callable, 'BaseStudentFreePeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		StudentFreePeer::addSelectColumns($c);
		$startcol2 = (StudentFreePeer::NUM_COLUMNS - StudentFreePeer::NUM_LAZY_LOAD_COLUMNS);

		CareerSchoolYearPeriodPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (CareerSchoolYearPeriodPeer::NUM_COLUMNS - CareerSchoolYearPeriodPeer::NUM_LAZY_LOAD_COLUMNS);

		CareerSchoolYearPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (CareerSchoolYearPeer::NUM_COLUMNS - CareerSchoolYearPeer::NUM_LAZY_LOAD_COLUMNS);

		CourseSubjectPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (CourseSubjectPeer::NUM_COLUMNS - CourseSubjectPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_PERIOD_ID,), array(CareerSchoolYearPeriodPeer::ID,), $join_behavior);
				$c->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_ID,), array(CareerSchoolYearPeer::ID,), $join_behavior);
				$c->addJoin(array(StudentFreePeer::COURSE_SUBJECT_ID,), array(CourseSubjectPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = StudentFreePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = StudentFreePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = StudentFreePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				StudentFreePeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined CareerSchoolYearPeriod rows

				$key2 = CareerSchoolYearPeriodPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = CareerSchoolYearPeriodPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = CareerSchoolYearPeriodPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					CareerSchoolYearPeriodPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (StudentFree) to the collection in $obj2 (CareerSchoolYearPeriod)
				$obj2->addStudentFree($obj1);

			} // if joined row is not null

				// Add objects for joined CareerSchoolYear rows

				$key3 = CareerSchoolYearPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = CareerSchoolYearPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = CareerSchoolYearPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					CareerSchoolYearPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (StudentFree) to the collection in $obj3 (CareerSchoolYear)
				$obj3->addStudentFree($obj1);

			} // if joined row is not null

				// Add objects for joined CourseSubject rows

				$key4 = CourseSubjectPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = CourseSubjectPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = CourseSubjectPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					CourseSubjectPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (StudentFree) to the collection in $obj4 (CourseSubject)
				$obj4->addStudentFree($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of StudentFree objects pre-filled with all related objects except CareerSchoolYearPeriod.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of StudentFree objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptCareerSchoolYearPeriod(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		StudentFreePeer::addSelectColumns($c);
		$startcol2 = (StudentFreePeer::NUM_COLUMNS - StudentFreePeer::NUM_LAZY_LOAD_COLUMNS);

		StudentPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (StudentPeer::NUM_COLUMNS - StudentPeer::NUM_LAZY_LOAD_COLUMNS);

		CareerSchoolYearPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (CareerSchoolYearPeer::NUM_COLUMNS - CareerSchoolYearPeer::NUM_LAZY_LOAD_COLUMNS);

		CourseSubjectPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (CourseSubjectPeer::NUM_COLUMNS - CourseSubjectPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(StudentFreePeer::STUDENT_ID,), array(StudentPeer::ID,), $join_behavior);
				$c->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_ID,), array(CareerSchoolYearPeer::ID,), $join_behavior);
				$c->addJoin(array(StudentFreePeer::COURSE_SUBJECT_ID,), array(CourseSubjectPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = StudentFreePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = StudentFreePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = StudentFreePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				StudentFreePeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Student rows

				$key2 = StudentPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = StudentPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = StudentPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					StudentPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (StudentFree) to the collection in $obj2 (Student)
				$obj2->addStudentFree($obj1);

			} // if joined row is not null

				// Add objects for joined CareerSchoolYear rows

				$key3 = CareerSchoolYearPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = CareerSchoolYearPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = CareerSchoolYearPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					CareerSchoolYearPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (StudentFree) to the collection in $obj3 (CareerSchoolYear)
				$obj3->addStudentFree($obj1);

			} // if joined row is not null

				// Add objects for joined CourseSubject rows

				$key4 = CourseSubjectPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = CourseSubjectPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = CourseSubjectPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					CourseSubjectPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (StudentFree) to the collection in $obj4 (CourseSubject)
				$obj4->addStudentFree($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of StudentFree objects pre-filled with all related objects except CareerSchoolYear.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of StudentFree objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptCareerSchoolYear(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		StudentFreePeer::addSelectColumns($c);
		$startcol2 = (StudentFreePeer::NUM_COLUMNS - StudentFreePeer::NUM_LAZY_LOAD_COLUMNS);

		StudentPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (StudentPeer::NUM_COLUMNS - StudentPeer::NUM_LAZY_LOAD_COLUMNS);

		CareerSchoolYearPeriodPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (CareerSchoolYearPeriodPeer::NUM_COLUMNS - CareerSchoolYearPeriodPeer::NUM_LAZY_LOAD_COLUMNS);

		CourseSubjectPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (CourseSubjectPeer::NUM_COLUMNS - CourseSubjectPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(StudentFreePeer::STUDENT_ID,), array(StudentPeer::ID,), $join_behavior);
				$c->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_PERIOD_ID,), array(CareerSchoolYearPeriodPeer::ID,), $join_behavior);
				$c->addJoin(array(StudentFreePeer::COURSE_SUBJECT_ID,), array(CourseSubjectPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = StudentFreePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = StudentFreePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = StudentFreePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				StudentFreePeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Student rows

				$key2 = StudentPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = StudentPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = StudentPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					StudentPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (StudentFree) to the collection in $obj2 (Student)
				$obj2->addStudentFree($obj1);

			} // if joined row is not null

				// Add objects for joined CareerSchoolYearPeriod rows

				$key3 = CareerSchoolYearPeriodPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = CareerSchoolYearPeriodPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = CareerSchoolYearPeriodPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					CareerSchoolYearPeriodPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (StudentFree) to the collection in $obj3 (CareerSchoolYearPeriod)
				$obj3->addStudentFree($obj1);

			} // if joined row is not null

				// Add objects for joined CourseSubject rows

				$key4 = CourseSubjectPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = CourseSubjectPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = CourseSubjectPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					CourseSubjectPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (StudentFree) to the collection in $obj4 (CourseSubject)
				$obj4->addStudentFree($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of StudentFree objects pre-filled with all related objects except CourseSubject.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of StudentFree objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptCourseSubject(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		StudentFreePeer::addSelectColumns($c);
		$startcol2 = (StudentFreePeer::NUM_COLUMNS - StudentFreePeer::NUM_LAZY_LOAD_COLUMNS);

		StudentPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (StudentPeer::NUM_COLUMNS - StudentPeer::NUM_LAZY_LOAD_COLUMNS);

		CareerSchoolYearPeriodPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (CareerSchoolYearPeriodPeer::NUM_COLUMNS - CareerSchoolYearPeriodPeer::NUM_LAZY_LOAD_COLUMNS);

		CareerSchoolYearPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (CareerSchoolYearPeer::NUM_COLUMNS - CareerSchoolYearPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(StudentFreePeer::STUDENT_ID,), array(StudentPeer::ID,), $join_behavior);
				$c->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_PERIOD_ID,), array(CareerSchoolYearPeriodPeer::ID,), $join_behavior);
				$c->addJoin(array(StudentFreePeer::CAREER_SCHOOL_YEAR_ID,), array(CareerSchoolYearPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = StudentFreePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = StudentFreePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = StudentFreePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				StudentFreePeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Student rows

				$key2 = StudentPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = StudentPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = StudentPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					StudentPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (StudentFree) to the collection in $obj2 (Student)
				$obj2->addStudentFree($obj1);

			} // if joined row is not null

				// Add objects for joined CareerSchoolYearPeriod rows

				$key3 = CareerSchoolYearPeriodPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = CareerSchoolYearPeriodPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = CareerSchoolYearPeriodPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					CareerSchoolYearPeriodPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (StudentFree) to the collection in $obj3 (CareerSchoolYearPeriod)
				$obj3->addStudentFree($obj1);

			} // if joined row is not null

				// Add objects for joined CareerSchoolYear rows

				$key4 = CareerSchoolYearPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = CareerSchoolYearPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = CareerSchoolYearPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					CareerSchoolYearPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (StudentFree) to the collection in $obj4 (CareerSchoolYear)
				$obj4->addStudentFree($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return StudentFreePeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a StudentFree or Criteria object.
	 *
	 * @param      mixed $values Criteria or StudentFree object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseStudentFreePeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseStudentFreePeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(StudentFreePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from StudentFree object
		}

		if ($criteria->containsKey(StudentFreePeer::ID) && $criteria->keyContainsValue(StudentFreePeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.StudentFreePeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseStudentFreePeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseStudentFreePeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a StudentFree or Criteria object.
	 *
	 * @param      mixed $values Criteria or StudentFree object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseStudentFreePeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseStudentFreePeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(StudentFreePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(StudentFreePeer::ID);
			$selectCriteria->add(StudentFreePeer::ID, $criteria->remove(StudentFreePeer::ID), $comparison);

		} else { // $values is StudentFree object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseStudentFreePeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseStudentFreePeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the student_free table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(StudentFreePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(StudentFreePeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a StudentFree or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or StudentFree object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(StudentFreePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			StudentFreePeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof StudentFree) {
			// invalidate the cache for this single object
			StudentFreePeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(StudentFreePeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				StudentFreePeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given StudentFree object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      StudentFree $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(StudentFree $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(StudentFreePeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(StudentFreePeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(StudentFreePeer::DATABASE_NAME, StudentFreePeer::TABLE_NAME, $columns);
    if ($res !== true) {
        foreach ($res as $failed) {
            $col = StudentFreePeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     StudentFree
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = StudentFreePeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(StudentFreePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(StudentFreePeer::DATABASE_NAME);
		$criteria->add(StudentFreePeer::ID, $pk);

		$v = StudentFreePeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(StudentFreePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(StudentFreePeer::DATABASE_NAME);
			$criteria->add(StudentFreePeer::ID, $pks, Criteria::IN);
			$objs = StudentFreePeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseStudentFreePeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the StudentFreePeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the StudentFreePeer class:
//
// Propel::getDatabaseMap(StudentFreePeer::DATABASE_NAME)->addTableBuilder(StudentFreePeer::TABLE_NAME, StudentFreePeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseStudentFreePeer::DATABASE_NAME)->addTableBuilder(BaseStudentFreePeer::TABLE_NAME, BaseStudentFreePeer::getMapBuilder());

