<?php

/**
 * Base class that represents a row from the 'pathway_student' table.
 *
 * Representa la inscripción de un alumno en una trayectoria
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Aug 23 21:09:09 2018
 *
 * @package    lib.model.om
 */
abstract class BasePathwayStudent extends BaseObject  implements Persistent {


  const PEER = 'PathwayStudentPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PathwayStudentPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the student_id field.
	 * @var        int
	 */
	protected $student_id;

	/**
	 * The value for the pathway_id field.
	 * @var        int
	 */
	protected $pathway_id;

	/**
	 * The value for the year field.
	 * @var        int
	 */
	protected $year;

	/**
	 * @var        Student
	 */
	protected $aStudent;

	/**
	 * @var        Pathway
	 */
	protected $aPathway;

	/**
	 * @var        array CourseSubjectStudentPathway[] Collection to store aggregation of CourseSubjectStudentPathway objects.
	 */
	protected $collCourseSubjectStudentPathways;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCourseSubjectStudentPathways.
	 */
	private $lastCourseSubjectStudentPathwayCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BasePathwayStudent object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [student_id] column value.
	 * Referencia al estudiante
	 * @return     int
	 */
	public function getStudentId()
	{
		return $this->student_id;
	}

	/**
	 * Get the [pathway_id] column value.
	 * Referencia a la trayectoria
	 * @return     int
	 */
	public function getPathwayId()
	{
		return $this->pathway_id;
	}

	/**
	 * Get the [year] column value.
	 * Representa el año para el cual el alumno se inscribe en trayectoria
	 * @return     int
	 */
	public function getYear()
	{
		return $this->year;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     PathwayStudent The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = PathwayStudentPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [student_id] column.
	 * Referencia al estudiante
	 * @param      int $v new value
	 * @return     PathwayStudent The current object (for fluent API support)
	 */
	public function setStudentId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->student_id !== $v) {
			$this->student_id = $v;
			$this->modifiedColumns[] = PathwayStudentPeer::STUDENT_ID;
		}

		if ($this->aStudent !== null && $this->aStudent->getId() !== $v) {
			$this->aStudent = null;
		}

		return $this;
	} // setStudentId()

	/**
	 * Set the value of [pathway_id] column.
	 * Referencia a la trayectoria
	 * @param      int $v new value
	 * @return     PathwayStudent The current object (for fluent API support)
	 */
	public function setPathwayId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->pathway_id !== $v) {
			$this->pathway_id = $v;
			$this->modifiedColumns[] = PathwayStudentPeer::PATHWAY_ID;
		}

		if ($this->aPathway !== null && $this->aPathway->getId() !== $v) {
			$this->aPathway = null;
		}

		return $this;
	} // setPathwayId()

	/**
	 * Set the value of [year] column.
	 * Representa el año para el cual el alumno se inscribe en trayectoria
	 * @param      int $v new value
	 * @return     PathwayStudent The current object (for fluent API support)
	 */
	public function setYear($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->year !== $v) {
			$this->year = $v;
			$this->modifiedColumns[] = PathwayStudentPeer::YEAR;
		}

		return $this;
	} // setYear()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->student_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->pathway_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->year = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 4; // 4 = PathwayStudentPeer::NUM_COLUMNS - PathwayStudentPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating PathwayStudent object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aStudent !== null && $this->student_id !== $this->aStudent->getId()) {
			$this->aStudent = null;
		}
		if ($this->aPathway !== null && $this->pathway_id !== $this->aPathway->getId()) {
			$this->aPathway = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PathwayStudentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PathwayStudentPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aStudent = null;
			$this->aPathway = null;
			$this->collCourseSubjectStudentPathways = null;
			$this->lastCourseSubjectStudentPathwayCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasePathwayStudent:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PathwayStudentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			PathwayStudentPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BasePathwayStudent:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasePathwayStudent:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PathwayStudentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BasePathwayStudent:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			PathwayStudentPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aStudent !== null) {
				if ($this->aStudent->isModified() || $this->aStudent->isNew()) {
					$affectedRows += $this->aStudent->save($con);
				}
				$this->setStudent($this->aStudent);
			}

			if ($this->aPathway !== null) {
				if ($this->aPathway->isModified() || $this->aPathway->isNew()) {
					$affectedRows += $this->aPathway->save($con);
				}
				$this->setPathway($this->aPathway);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = PathwayStudentPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PathwayStudentPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += PathwayStudentPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collCourseSubjectStudentPathways !== null) {
				foreach ($this->collCourseSubjectStudentPathways as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aStudent !== null) {
				if (!$this->aStudent->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aStudent->getValidationFailures());
				}
			}

			if ($this->aPathway !== null) {
				if (!$this->aPathway->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPathway->getValidationFailures());
				}
			}


			if (($retval = PathwayStudentPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collCourseSubjectStudentPathways !== null) {
					foreach ($this->collCourseSubjectStudentPathways as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PathwayStudentPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getStudentId();
				break;
			case 2:
				return $this->getPathwayId();
				break;
			case 3:
				return $this->getYear();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = PathwayStudentPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getStudentId(),
			$keys[2] => $this->getPathwayId(),
			$keys[3] => $this->getYear(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PathwayStudentPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setStudentId($value);
				break;
			case 2:
				$this->setPathwayId($value);
				break;
			case 3:
				$this->setYear($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PathwayStudentPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setStudentId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setPathwayId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setYear($arr[$keys[3]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PathwayStudentPeer::DATABASE_NAME);

		if ($this->isColumnModified(PathwayStudentPeer::ID)) $criteria->add(PathwayStudentPeer::ID, $this->id);
		if ($this->isColumnModified(PathwayStudentPeer::STUDENT_ID)) $criteria->add(PathwayStudentPeer::STUDENT_ID, $this->student_id);
		if ($this->isColumnModified(PathwayStudentPeer::PATHWAY_ID)) $criteria->add(PathwayStudentPeer::PATHWAY_ID, $this->pathway_id);
		if ($this->isColumnModified(PathwayStudentPeer::YEAR)) $criteria->add(PathwayStudentPeer::YEAR, $this->year);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PathwayStudentPeer::DATABASE_NAME);

		$criteria->add(PathwayStudentPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of PathwayStudent (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setStudentId($this->student_id);

		$copyObj->setPathwayId($this->pathway_id);

		$copyObj->setYear($this->year);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getCourseSubjectStudentPathways() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCourseSubjectStudentPathway($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     PathwayStudent Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PathwayStudentPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PathwayStudentPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Student object.
	 *
	 * @param      Student $v
	 * @return     PathwayStudent The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setStudent(Student $v = null)
	{
		if ($v === null) {
			$this->setStudentId(NULL);
		} else {
			$this->setStudentId($v->getId());
		}

		$this->aStudent = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Student object, it will not be re-added.
		if ($v !== null) {
			$v->addPathwayStudent($this);
		}

		return $this;
	}


	/**
	 * Get the associated Student object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Student The associated Student object.
	 * @throws     PropelException
	 */
	public function getStudent(PropelPDO $con = null)
	{
		if ($this->aStudent === null && ($this->student_id !== null)) {
			$c = new Criteria(StudentPeer::DATABASE_NAME);
			$c->add(StudentPeer::ID, $this->student_id);
			$this->aStudent = StudentPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aStudent->addPathwayStudents($this);
			 */
		}
		return $this->aStudent;
	}

	/**
	 * Declares an association between this object and a Pathway object.
	 *
	 * @param      Pathway $v
	 * @return     PathwayStudent The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPathway(Pathway $v = null)
	{
		if ($v === null) {
			$this->setPathwayId(NULL);
		} else {
			$this->setPathwayId($v->getId());
		}

		$this->aPathway = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Pathway object, it will not be re-added.
		if ($v !== null) {
			$v->addPathwayStudent($this);
		}

		return $this;
	}


	/**
	 * Get the associated Pathway object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Pathway The associated Pathway object.
	 * @throws     PropelException
	 */
	public function getPathway(PropelPDO $con = null)
	{
		if ($this->aPathway === null && ($this->pathway_id !== null)) {
			$c = new Criteria(PathwayPeer::DATABASE_NAME);
			$c->add(PathwayPeer::ID, $this->pathway_id);
			$this->aPathway = PathwayPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPathway->addPathwayStudents($this);
			 */
		}
		return $this->aPathway;
	}

	/**
	 * Clears out the collCourseSubjectStudentPathways collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCourseSubjectStudentPathways()
	 */
	public function clearCourseSubjectStudentPathways()
	{
		$this->collCourseSubjectStudentPathways = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCourseSubjectStudentPathways collection (array).
	 *
	 * By default this just sets the collCourseSubjectStudentPathways collection to an empty array (like clearcollCourseSubjectStudentPathways());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCourseSubjectStudentPathways()
	{
		$this->collCourseSubjectStudentPathways = array();
	}

	/**
	 * Gets an array of CourseSubjectStudentPathway objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this PathwayStudent has previously been saved, it will retrieve
	 * related CourseSubjectStudentPathways from storage. If this PathwayStudent is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array CourseSubjectStudentPathway[]
	 * @throws     PropelException
	 */
	public function getCourseSubjectStudentPathways($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PathwayStudentPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCourseSubjectStudentPathways === null) {
			if ($this->isNew()) {
			   $this->collCourseSubjectStudentPathways = array();
			} else {

				$criteria->add(CourseSubjectStudentPathwayPeer::PATHWAY_STUDENT_ID, $this->id);

				CourseSubjectStudentPathwayPeer::addSelectColumns($criteria);
				$this->collCourseSubjectStudentPathways = CourseSubjectStudentPathwayPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CourseSubjectStudentPathwayPeer::PATHWAY_STUDENT_ID, $this->id);

				CourseSubjectStudentPathwayPeer::addSelectColumns($criteria);
				if (!isset($this->lastCourseSubjectStudentPathwayCriteria) || !$this->lastCourseSubjectStudentPathwayCriteria->equals($criteria)) {
					$this->collCourseSubjectStudentPathways = CourseSubjectStudentPathwayPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCourseSubjectStudentPathwayCriteria = $criteria;
		return $this->collCourseSubjectStudentPathways;
	}

	/**
	 * Returns the number of related CourseSubjectStudentPathway objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related CourseSubjectStudentPathway objects.
	 * @throws     PropelException
	 */
	public function countCourseSubjectStudentPathways(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PathwayStudentPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCourseSubjectStudentPathways === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CourseSubjectStudentPathwayPeer::PATHWAY_STUDENT_ID, $this->id);

				$count = CourseSubjectStudentPathwayPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CourseSubjectStudentPathwayPeer::PATHWAY_STUDENT_ID, $this->id);

				if (!isset($this->lastCourseSubjectStudentPathwayCriteria) || !$this->lastCourseSubjectStudentPathwayCriteria->equals($criteria)) {
					$count = CourseSubjectStudentPathwayPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collCourseSubjectStudentPathways);
				}
			} else {
				$count = count($this->collCourseSubjectStudentPathways);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a CourseSubjectStudentPathway object to this object
	 * through the CourseSubjectStudentPathway foreign key attribute.
	 *
	 * @param      CourseSubjectStudentPathway $l CourseSubjectStudentPathway
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCourseSubjectStudentPathway(CourseSubjectStudentPathway $l)
	{
		if ($this->collCourseSubjectStudentPathways === null) {
			$this->initCourseSubjectStudentPathways();
		}
		if (!in_array($l, $this->collCourseSubjectStudentPathways, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCourseSubjectStudentPathways, $l);
			$l->setPathwayStudent($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this PathwayStudent is new, it will return
	 * an empty collection; or if this PathwayStudent has previously
	 * been saved, it will retrieve related CourseSubjectStudentPathways from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in PathwayStudent.
	 */
	public function getCourseSubjectStudentPathwaysJoinStudent($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PathwayStudentPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCourseSubjectStudentPathways === null) {
			if ($this->isNew()) {
				$this->collCourseSubjectStudentPathways = array();
			} else {

				$criteria->add(CourseSubjectStudentPathwayPeer::PATHWAY_STUDENT_ID, $this->id);

				$this->collCourseSubjectStudentPathways = CourseSubjectStudentPathwayPeer::doSelectJoinStudent($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CourseSubjectStudentPathwayPeer::PATHWAY_STUDENT_ID, $this->id);

			if (!isset($this->lastCourseSubjectStudentPathwayCriteria) || !$this->lastCourseSubjectStudentPathwayCriteria->equals($criteria)) {
				$this->collCourseSubjectStudentPathways = CourseSubjectStudentPathwayPeer::doSelectJoinStudent($criteria, $con, $join_behavior);
			}
		}
		$this->lastCourseSubjectStudentPathwayCriteria = $criteria;

		return $this->collCourseSubjectStudentPathways;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this PathwayStudent is new, it will return
	 * an empty collection; or if this PathwayStudent has previously
	 * been saved, it will retrieve related CourseSubjectStudentPathways from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in PathwayStudent.
	 */
	public function getCourseSubjectStudentPathwaysJoinCourseSubject($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PathwayStudentPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCourseSubjectStudentPathways === null) {
			if ($this->isNew()) {
				$this->collCourseSubjectStudentPathways = array();
			} else {

				$criteria->add(CourseSubjectStudentPathwayPeer::PATHWAY_STUDENT_ID, $this->id);

				$this->collCourseSubjectStudentPathways = CourseSubjectStudentPathwayPeer::doSelectJoinCourseSubject($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CourseSubjectStudentPathwayPeer::PATHWAY_STUDENT_ID, $this->id);

			if (!isset($this->lastCourseSubjectStudentPathwayCriteria) || !$this->lastCourseSubjectStudentPathwayCriteria->equals($criteria)) {
				$this->collCourseSubjectStudentPathways = CourseSubjectStudentPathwayPeer::doSelectJoinCourseSubject($criteria, $con, $join_behavior);
			}
		}
		$this->lastCourseSubjectStudentPathwayCriteria = $criteria;

		return $this->collCourseSubjectStudentPathways;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collCourseSubjectStudentPathways) {
				foreach ((array) $this->collCourseSubjectStudentPathways as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collCourseSubjectStudentPathways = null;
			$this->aStudent = null;
			$this->aPathway = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BasePathwayStudent:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BasePathwayStudent::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BasePathwayStudent
