<?php

/**
 * Base class that represents a row from the 'career_student' table.
 *
 * Cada tupla representa un inscripto a una carrera
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Aug 23 21:09:09 2018
 *
 * @package    lib.model.om
 */
abstract class BaseCareerStudent extends BaseObject  implements Persistent {


  const PEER = 'CareerStudentPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        CareerStudentPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the career_id field.
	 * @var        int
	 */
	protected $career_id;

	/**
	 * The value for the student_id field.
	 * @var        int
	 */
	protected $student_id;

	/**
	 * The value for the orientation_id field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $orientation_id;

	/**
	 * The value for the sub_orientation_id field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $sub_orientation_id;

	/**
	 * The value for the orientation_change_observations field.
	 * @var        string
	 */
	protected $orientation_change_observations;

	/**
	 * The value for the start_year field.
	 * Note: this column has a database default value of: 1
	 * @var        int
	 */
	protected $start_year;

	/**
	 * The value for the file_number field.
	 * @var        string
	 */
	protected $file_number;

	/**
	 * The value for the status field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $status;

	/**
	 * The value for the graduation_school_year_id field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $graduation_school_year_id;

	/**
	 * @var        Career
	 */
	protected $aCareer;

	/**
	 * @var        Student
	 */
	protected $aStudent;

	/**
	 * @var        Orientation
	 */
	protected $aOrientation;

	/**
	 * @var        SubOrientation
	 */
	protected $aSubOrientation;

	/**
	 * @var        SchoolYear
	 */
	protected $aSchoolYear;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseCareerStudent object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->orientation_id = 0;
		$this->sub_orientation_id = 0;
		$this->start_year = 1;
		$this->status = 0;
		$this->graduation_school_year_id = 0;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [career_id] column value.
	 * Referencia a la carrera
	 * @return     int
	 */
	public function getCareerId()
	{
		return $this->career_id;
	}

	/**
	 * Get the [student_id] column value.
	 * Referencia al estudiante
	 * @return     int
	 */
	public function getStudentId()
	{
		return $this->student_id;
	}

	/**
	 * Get the [orientation_id] column value.
	 * 
	 * @return     int
	 */
	public function getOrientationId()
	{
		return $this->orientation_id;
	}

	/**
	 * Get the [sub_orientation_id] column value.
	 * 
	 * @return     int
	 */
	public function getSubOrientationId()
	{
		return $this->sub_orientation_id;
	}

	/**
	 * Get the [orientation_change_observations] column value.
	 * 
	 * @return     string
	 */
	public function getOrientationChangeObservations()
	{
		return $this->orientation_change_observations;
	}

	/**
	 * Get the [start_year] column value.
	 * 
	 * @return     int
	 */
	public function getStartYear()
	{
		return $this->start_year;
	}

	/**
	 * Get the [file_number] column value.
	 * Número de alumno en la carrera (si usa uno único para todo el colegio entonces se copia del global file number de student)
	 * @return     string
	 */
	public function getFileNumber()
	{
		return $this->file_number;
	}

	/**
	 * Get the [status] column value.
	 * El estado de un alumno en una carrera (CURSANDO , GRADUADO)
	 * @return     int
	 */
	public function getStatus()
	{
		return $this->status;
	}

	/**
	 * Get the [graduation_school_year_id] column value.
	 * 
	 * @return     int
	 */
	public function getGraduationSchoolYearId()
	{
		return $this->graduation_school_year_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     CareerStudent The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = CareerStudentPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     CareerStudent The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = CareerStudentPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Set the value of [career_id] column.
	 * Referencia a la carrera
	 * @param      int $v new value
	 * @return     CareerStudent The current object (for fluent API support)
	 */
	public function setCareerId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->career_id !== $v) {
			$this->career_id = $v;
			$this->modifiedColumns[] = CareerStudentPeer::CAREER_ID;
		}

		if ($this->aCareer !== null && $this->aCareer->getId() !== $v) {
			$this->aCareer = null;
		}

		return $this;
	} // setCareerId()

	/**
	 * Set the value of [student_id] column.
	 * Referencia al estudiante
	 * @param      int $v new value
	 * @return     CareerStudent The current object (for fluent API support)
	 */
	public function setStudentId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->student_id !== $v) {
			$this->student_id = $v;
			$this->modifiedColumns[] = CareerStudentPeer::STUDENT_ID;
		}

		if ($this->aStudent !== null && $this->aStudent->getId() !== $v) {
			$this->aStudent = null;
		}

		return $this;
	} // setStudentId()

	/**
	 * Set the value of [orientation_id] column.
	 * 
	 * @param      int $v new value
	 * @return     CareerStudent The current object (for fluent API support)
	 */
	public function setOrientationId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->orientation_id !== $v || $v === 0) {
			$this->orientation_id = $v;
			$this->modifiedColumns[] = CareerStudentPeer::ORIENTATION_ID;
		}

		if ($this->aOrientation !== null && $this->aOrientation->getId() !== $v) {
			$this->aOrientation = null;
		}

		return $this;
	} // setOrientationId()

	/**
	 * Set the value of [sub_orientation_id] column.
	 * 
	 * @param      int $v new value
	 * @return     CareerStudent The current object (for fluent API support)
	 */
	public function setSubOrientationId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->sub_orientation_id !== $v || $v === 0) {
			$this->sub_orientation_id = $v;
			$this->modifiedColumns[] = CareerStudentPeer::SUB_ORIENTATION_ID;
		}

		if ($this->aSubOrientation !== null && $this->aSubOrientation->getId() !== $v) {
			$this->aSubOrientation = null;
		}

		return $this;
	} // setSubOrientationId()

	/**
	 * Set the value of [orientation_change_observations] column.
	 * 
	 * @param      string $v new value
	 * @return     CareerStudent The current object (for fluent API support)
	 */
	public function setOrientationChangeObservations($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->orientation_change_observations !== $v) {
			$this->orientation_change_observations = $v;
			$this->modifiedColumns[] = CareerStudentPeer::ORIENTATION_CHANGE_OBSERVATIONS;
		}

		return $this;
	} // setOrientationChangeObservations()

	/**
	 * Set the value of [start_year] column.
	 * 
	 * @param      int $v new value
	 * @return     CareerStudent The current object (for fluent API support)
	 */
	public function setStartYear($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->start_year !== $v || $v === 1) {
			$this->start_year = $v;
			$this->modifiedColumns[] = CareerStudentPeer::START_YEAR;
		}

		return $this;
	} // setStartYear()

	/**
	 * Set the value of [file_number] column.
	 * Número de alumno en la carrera (si usa uno único para todo el colegio entonces se copia del global file number de student)
	 * @param      string $v new value
	 * @return     CareerStudent The current object (for fluent API support)
	 */
	public function setFileNumber($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->file_number !== $v) {
			$this->file_number = $v;
			$this->modifiedColumns[] = CareerStudentPeer::FILE_NUMBER;
		}

		return $this;
	} // setFileNumber()

	/**
	 * Set the value of [status] column.
	 * El estado de un alumno en una carrera (CURSANDO , GRADUADO)
	 * @param      int $v new value
	 * @return     CareerStudent The current object (for fluent API support)
	 */
	public function setStatus($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->status !== $v || $v === 0) {
			$this->status = $v;
			$this->modifiedColumns[] = CareerStudentPeer::STATUS;
		}

		return $this;
	} // setStatus()

	/**
	 * Set the value of [graduation_school_year_id] column.
	 * 
	 * @param      int $v new value
	 * @return     CareerStudent The current object (for fluent API support)
	 */
	public function setGraduationSchoolYearId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->graduation_school_year_id !== $v || $v === 0) {
			$this->graduation_school_year_id = $v;
			$this->modifiedColumns[] = CareerStudentPeer::GRADUATION_SCHOOL_YEAR_ID;
		}

		if ($this->aSchoolYear !== null && $this->aSchoolYear->getId() !== $v) {
			$this->aSchoolYear = null;
		}

		return $this;
	} // setGraduationSchoolYearId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(CareerStudentPeer::ORIENTATION_ID,CareerStudentPeer::SUB_ORIENTATION_ID,CareerStudentPeer::START_YEAR,CareerStudentPeer::STATUS,CareerStudentPeer::GRADUATION_SCHOOL_YEAR_ID))) {
				return false;
			}

			if ($this->orientation_id !== 0) {
				return false;
			}

			if ($this->sub_orientation_id !== 0) {
				return false;
			}

			if ($this->start_year !== 1) {
				return false;
			}

			if ($this->status !== 0) {
				return false;
			}

			if ($this->graduation_school_year_id !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->created_at = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->career_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->student_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->orientation_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->sub_orientation_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->orientation_change_observations = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->start_year = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->file_number = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->status = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->graduation_school_year_id = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 11; // 11 = CareerStudentPeer::NUM_COLUMNS - CareerStudentPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating CareerStudent object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aCareer !== null && $this->career_id !== $this->aCareer->getId()) {
			$this->aCareer = null;
		}
		if ($this->aStudent !== null && $this->student_id !== $this->aStudent->getId()) {
			$this->aStudent = null;
		}
		if ($this->aOrientation !== null && $this->orientation_id !== $this->aOrientation->getId()) {
			$this->aOrientation = null;
		}
		if ($this->aSubOrientation !== null && $this->sub_orientation_id !== $this->aSubOrientation->getId()) {
			$this->aSubOrientation = null;
		}
		if ($this->aSchoolYear !== null && $this->graduation_school_year_id !== $this->aSchoolYear->getId()) {
			$this->aSchoolYear = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CareerStudentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = CareerStudentPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aCareer = null;
			$this->aStudent = null;
			$this->aOrientation = null;
			$this->aSubOrientation = null;
			$this->aSchoolYear = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCareerStudent:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CareerStudentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			CareerStudentPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseCareerStudent:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCareerStudent:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(CareerStudentPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CareerStudentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseCareerStudent:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			CareerStudentPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCareer !== null) {
				if ($this->aCareer->isModified() || $this->aCareer->isNew()) {
					$affectedRows += $this->aCareer->save($con);
				}
				$this->setCareer($this->aCareer);
			}

			if ($this->aStudent !== null) {
				if ($this->aStudent->isModified() || $this->aStudent->isNew()) {
					$affectedRows += $this->aStudent->save($con);
				}
				$this->setStudent($this->aStudent);
			}

			if ($this->aOrientation !== null) {
				if ($this->aOrientation->isModified() || $this->aOrientation->isNew()) {
					$affectedRows += $this->aOrientation->save($con);
				}
				$this->setOrientation($this->aOrientation);
			}

			if ($this->aSubOrientation !== null) {
				if ($this->aSubOrientation->isModified() || $this->aSubOrientation->isNew()) {
					$affectedRows += $this->aSubOrientation->save($con);
				}
				$this->setSubOrientation($this->aSubOrientation);
			}

			if ($this->aSchoolYear !== null) {
				if ($this->aSchoolYear->isModified() || $this->aSchoolYear->isNew()) {
					$affectedRows += $this->aSchoolYear->save($con);
				}
				$this->setSchoolYear($this->aSchoolYear);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = CareerStudentPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = CareerStudentPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += CareerStudentPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCareer !== null) {
				if (!$this->aCareer->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCareer->getValidationFailures());
				}
			}

			if ($this->aStudent !== null) {
				if (!$this->aStudent->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aStudent->getValidationFailures());
				}
			}

			if ($this->aOrientation !== null) {
				if (!$this->aOrientation->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aOrientation->getValidationFailures());
				}
			}

			if ($this->aSubOrientation !== null) {
				if (!$this->aSubOrientation->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSubOrientation->getValidationFailures());
				}
			}

			if ($this->aSchoolYear !== null) {
				if (!$this->aSchoolYear->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSchoolYear->getValidationFailures());
				}
			}


			if (($retval = CareerStudentPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CareerStudentPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getCreatedAt();
				break;
			case 2:
				return $this->getCareerId();
				break;
			case 3:
				return $this->getStudentId();
				break;
			case 4:
				return $this->getOrientationId();
				break;
			case 5:
				return $this->getSubOrientationId();
				break;
			case 6:
				return $this->getOrientationChangeObservations();
				break;
			case 7:
				return $this->getStartYear();
				break;
			case 8:
				return $this->getFileNumber();
				break;
			case 9:
				return $this->getStatus();
				break;
			case 10:
				return $this->getGraduationSchoolYearId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = CareerStudentPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getCreatedAt(),
			$keys[2] => $this->getCareerId(),
			$keys[3] => $this->getStudentId(),
			$keys[4] => $this->getOrientationId(),
			$keys[5] => $this->getSubOrientationId(),
			$keys[6] => $this->getOrientationChangeObservations(),
			$keys[7] => $this->getStartYear(),
			$keys[8] => $this->getFileNumber(),
			$keys[9] => $this->getStatus(),
			$keys[10] => $this->getGraduationSchoolYearId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CareerStudentPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setCreatedAt($value);
				break;
			case 2:
				$this->setCareerId($value);
				break;
			case 3:
				$this->setStudentId($value);
				break;
			case 4:
				$this->setOrientationId($value);
				break;
			case 5:
				$this->setSubOrientationId($value);
				break;
			case 6:
				$this->setOrientationChangeObservations($value);
				break;
			case 7:
				$this->setStartYear($value);
				break;
			case 8:
				$this->setFileNumber($value);
				break;
			case 9:
				$this->setStatus($value);
				break;
			case 10:
				$this->setGraduationSchoolYearId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = CareerStudentPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCreatedAt($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCareerId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setStudentId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setOrientationId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setSubOrientationId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setOrientationChangeObservations($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setStartYear($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setFileNumber($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setStatus($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setGraduationSchoolYearId($arr[$keys[10]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(CareerStudentPeer::DATABASE_NAME);

		if ($this->isColumnModified(CareerStudentPeer::ID)) $criteria->add(CareerStudentPeer::ID, $this->id);
		if ($this->isColumnModified(CareerStudentPeer::CREATED_AT)) $criteria->add(CareerStudentPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(CareerStudentPeer::CAREER_ID)) $criteria->add(CareerStudentPeer::CAREER_ID, $this->career_id);
		if ($this->isColumnModified(CareerStudentPeer::STUDENT_ID)) $criteria->add(CareerStudentPeer::STUDENT_ID, $this->student_id);
		if ($this->isColumnModified(CareerStudentPeer::ORIENTATION_ID)) $criteria->add(CareerStudentPeer::ORIENTATION_ID, $this->orientation_id);
		if ($this->isColumnModified(CareerStudentPeer::SUB_ORIENTATION_ID)) $criteria->add(CareerStudentPeer::SUB_ORIENTATION_ID, $this->sub_orientation_id);
		if ($this->isColumnModified(CareerStudentPeer::ORIENTATION_CHANGE_OBSERVATIONS)) $criteria->add(CareerStudentPeer::ORIENTATION_CHANGE_OBSERVATIONS, $this->orientation_change_observations);
		if ($this->isColumnModified(CareerStudentPeer::START_YEAR)) $criteria->add(CareerStudentPeer::START_YEAR, $this->start_year);
		if ($this->isColumnModified(CareerStudentPeer::FILE_NUMBER)) $criteria->add(CareerStudentPeer::FILE_NUMBER, $this->file_number);
		if ($this->isColumnModified(CareerStudentPeer::STATUS)) $criteria->add(CareerStudentPeer::STATUS, $this->status);
		if ($this->isColumnModified(CareerStudentPeer::GRADUATION_SCHOOL_YEAR_ID)) $criteria->add(CareerStudentPeer::GRADUATION_SCHOOL_YEAR_ID, $this->graduation_school_year_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(CareerStudentPeer::DATABASE_NAME);

		$criteria->add(CareerStudentPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of CareerStudent (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setCareerId($this->career_id);

		$copyObj->setStudentId($this->student_id);

		$copyObj->setOrientationId($this->orientation_id);

		$copyObj->setSubOrientationId($this->sub_orientation_id);

		$copyObj->setOrientationChangeObservations($this->orientation_change_observations);

		$copyObj->setStartYear($this->start_year);

		$copyObj->setFileNumber($this->file_number);

		$copyObj->setStatus($this->status);

		$copyObj->setGraduationSchoolYearId($this->graduation_school_year_id);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     CareerStudent Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     CareerStudentPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new CareerStudentPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Career object.
	 *
	 * @param      Career $v
	 * @return     CareerStudent The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCareer(Career $v = null)
	{
		if ($v === null) {
			$this->setCareerId(NULL);
		} else {
			$this->setCareerId($v->getId());
		}

		$this->aCareer = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Career object, it will not be re-added.
		if ($v !== null) {
			$v->addCareerStudent($this);
		}

		return $this;
	}


	/**
	 * Get the associated Career object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Career The associated Career object.
	 * @throws     PropelException
	 */
	public function getCareer(PropelPDO $con = null)
	{
		if ($this->aCareer === null && ($this->career_id !== null)) {
			$c = new Criteria(CareerPeer::DATABASE_NAME);
			$c->add(CareerPeer::ID, $this->career_id);
			$this->aCareer = CareerPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCareer->addCareerStudents($this);
			 */
		}
		return $this->aCareer;
	}

	/**
	 * Declares an association between this object and a Student object.
	 *
	 * @param      Student $v
	 * @return     CareerStudent The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setStudent(Student $v = null)
	{
		if ($v === null) {
			$this->setStudentId(NULL);
		} else {
			$this->setStudentId($v->getId());
		}

		$this->aStudent = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Student object, it will not be re-added.
		if ($v !== null) {
			$v->addCareerStudent($this);
		}

		return $this;
	}


	/**
	 * Get the associated Student object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Student The associated Student object.
	 * @throws     PropelException
	 */
	public function getStudent(PropelPDO $con = null)
	{
		if ($this->aStudent === null && ($this->student_id !== null)) {
			$c = new Criteria(StudentPeer::DATABASE_NAME);
			$c->add(StudentPeer::ID, $this->student_id);
			$this->aStudent = StudentPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aStudent->addCareerStudents($this);
			 */
		}
		return $this->aStudent;
	}

	/**
	 * Declares an association between this object and a Orientation object.
	 *
	 * @param      Orientation $v
	 * @return     CareerStudent The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setOrientation(Orientation $v = null)
	{
		if ($v === null) {
			$this->setOrientationId(0);
		} else {
			$this->setOrientationId($v->getId());
		}

		$this->aOrientation = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Orientation object, it will not be re-added.
		if ($v !== null) {
			$v->addCareerStudent($this);
		}

		return $this;
	}


	/**
	 * Get the associated Orientation object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Orientation The associated Orientation object.
	 * @throws     PropelException
	 */
	public function getOrientation(PropelPDO $con = null)
	{
		if ($this->aOrientation === null && ($this->orientation_id !== null)) {
			$c = new Criteria(OrientationPeer::DATABASE_NAME);
			$c->add(OrientationPeer::ID, $this->orientation_id);
			$this->aOrientation = OrientationPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aOrientation->addCareerStudents($this);
			 */
		}
		return $this->aOrientation;
	}

	/**
	 * Declares an association between this object and a SubOrientation object.
	 *
	 * @param      SubOrientation $v
	 * @return     CareerStudent The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSubOrientation(SubOrientation $v = null)
	{
		if ($v === null) {
			$this->setSubOrientationId(0);
		} else {
			$this->setSubOrientationId($v->getId());
		}

		$this->aSubOrientation = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the SubOrientation object, it will not be re-added.
		if ($v !== null) {
			$v->addCareerStudent($this);
		}

		return $this;
	}


	/**
	 * Get the associated SubOrientation object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     SubOrientation The associated SubOrientation object.
	 * @throws     PropelException
	 */
	public function getSubOrientation(PropelPDO $con = null)
	{
		if ($this->aSubOrientation === null && ($this->sub_orientation_id !== null)) {
			$c = new Criteria(SubOrientationPeer::DATABASE_NAME);
			$c->add(SubOrientationPeer::ID, $this->sub_orientation_id);
			$this->aSubOrientation = SubOrientationPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aSubOrientation->addCareerStudents($this);
			 */
		}
		return $this->aSubOrientation;
	}

	/**
	 * Declares an association between this object and a SchoolYear object.
	 *
	 * @param      SchoolYear $v
	 * @return     CareerStudent The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSchoolYear(SchoolYear $v = null)
	{
		if ($v === null) {
			$this->setGraduationSchoolYearId(0);
		} else {
			$this->setGraduationSchoolYearId($v->getId());
		}

		$this->aSchoolYear = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the SchoolYear object, it will not be re-added.
		if ($v !== null) {
			$v->addCareerStudent($this);
		}

		return $this;
	}


	/**
	 * Get the associated SchoolYear object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     SchoolYear The associated SchoolYear object.
	 * @throws     PropelException
	 */
	public function getSchoolYear(PropelPDO $con = null)
	{
		if ($this->aSchoolYear === null && ($this->graduation_school_year_id !== null)) {
			$c = new Criteria(SchoolYearPeer::DATABASE_NAME);
			$c->add(SchoolYearPeer::ID, $this->graduation_school_year_id);
			$this->aSchoolYear = SchoolYearPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aSchoolYear->addCareerStudents($this);
			 */
		}
		return $this->aSchoolYear;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aCareer = null;
			$this->aStudent = null;
			$this->aOrientation = null;
			$this->aSubOrientation = null;
			$this->aSchoolYear = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseCareerStudent:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseCareerStudent::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseCareerStudent
