<?php
// auto-generated by sfSecurityConfigHandler
// date: 2018/08/23 21:34:17
$this->security = array (
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 'show_teacher',
    ),
  ),
  'new' => 
  array (
    'credentials' => 
    array (
      0 => 'edit_teacher',
    ),
  ),
  'create' => 
  array (
    'credentials' => 
    array (
      0 => 'edit_teacher',
    ),
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 'edit_teacher',
    ),
  ),
  'update' => 
  array (
    'credentials' => 
    array (
      0 => 'edit_teacher',
    ),
  ),
  'show' => 
  array (
    'credentials' => 
    array (
      0 => 'show_teacher',
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 'edit_teacher',
    ),
  ),
  'personactivation' => 
  array (
    'credentials' => 
    array (
      0 => 'edit_teacher',
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
